# Assignment 4
## Description
In this assignment you must read in a file of metropolitan regions and associated sports teams from [assets/wikipedia_data.html](assets/wikipedia_data.html) and answer some questions about each metropolitan region. Each of these regions may have one or more teams from the "Big 4": NFL (football, in [assets/nfl.csv](assets/nfl.csv)), MLB (baseball, in [assets/mlb.csv](assets/mlb.csv)), NBA (basketball, in [assets/nba.csv](assets/nba.csv) or NHL (hockey, in [assets/nhl.csv](assets/nhl.csv)). Please keep in mind that all questions are from the perspective of the metropolitan region, and that this file is the "source of authority" for the location of a given sports team. Thus teams which are commonly known by a different area (e.g. "Oakland Raiders") need to be mapped into the metropolitan region given (e.g. San Francisco Bay Area). This will require some human data understanding outside of the data you've been given (e.g. you will have to hand-code some names, and might need to google to find out where teams are)!

For each sport I would like you to answer the question: **what is the win/loss ratio's correlation with the population of the city it is in?** Win/Loss ratio refers to the number of wins over the number of wins plus the number of losses. Remember that to calculate the correlation with [`pearsonr`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.pearsonr.html), so you are going to send in two ordered lists of values, the populations from the wikipedia_data.html file and the win/loss ratio for a given sport in the same order. Average the win/loss ratios for those cities which have multiple teams of a single sport. Each sport is worth an equal amount in this assignment (20%\*4=80%) of the grade for this assignment. You should only use data **from year 2018** for your analysis -- this is important!

## Notes

1. Do not include data about the MLS or CFL in any of the work you are doing, we're only interested in the Big 4 in this assignment.
2. I highly suggest that you first tackle the four correlation questions in order, as they are all similar and worth the majority of grades for this assignment. This is by design!
3. It's fair game to talk with peers about high level strategy as well as the relationship between metropolitan areas and sports teams. However, do not post code solving aspects of the assignment (including such as dictionaries mapping areas to teams, or regexes which will clean up names).
4. There may be more teams than the assert statements test, remember to collapse multiple teams in one city into a single value!

As this assignment utilizes global variables in the skeleton code, to avoid having errors in your code you can either:

1. You can place all of your code within the function definitions for all of the questions (other than import statements).
2. You can create copies of all the global variables with the copy() method and proceed as usual.

## Question 1
For this question, calculate the win/loss ratio's correlation with the population of the city it is in for the **NHL** using **2018** data.

In [1]:
import pandas as pd
import numpy as np
import scipy.stats as stats
import re

nhl_df=pd.read_csv("nhl.csv")
cities=pd.read_html("wikipedia_data.html")[1]
cities=cities.iloc[:-1,[0,3,5,6,7,8]]

cities = cities.replace(to_replace="\[.*?\]", value= "", regex= True )
cities = cities.replace(to_replace="(?<=[a-z])(?=[A-Z])", value=" ", regex=True) #locally I got texts like "GianJets" instead of "Giant Jets" so I added a space between lower and upper case letters

#REMOVING BLANK SPACES FROM THE COLUMNS
cities.columns = cities.columns.str.strip()

cities.rename(columns = {'Population (2016 est.)[8]': 'Population 2016'}, inplace=True)

def nhl_correlation(): 
    # YOUR CODE HERE
    raise NotImplementedError()
    
    population_by_region = [] # pass in metropolitan area population from cities
    win_loss_by_region = [] # pass in win/loss ratio from nhl_df in the same order as cities["Metropolitan area"]

    assert len(population_by_region) == len(win_loss_by_region), "Q1: Your lists must be the same length"
    assert len(population_by_region) == 28, "Q1: There should be 28 teams being analysed for NHL"
    
    return stats.pearsonr(population_by_region, win_loss_by_region)

cities#.iloc[2]["MLB"]

,Metropolitan area,Population 2016,NFL,MLB,NBA,NHL
0,New York City,20153634,Giants Jets,Yankees Mets,Knicks Nets,Rangers Islanders Devils
1,Los Angeles,13310447,Rams Chargers,Dodgers Angels,Lakers Clippers,Kings Ducks
2,San Francisco Bay Area,6657982,49ers Raiders,Giants Athletics,Warriors,Sharks
3,Chicago,9512999,Bears,Cubs White Sox,Bulls,Blackhawks
4,Dallas–Fort Worth,7233323,Cowboys,Rangers,Mavericks,Stars
5,"Washington, D.C.",6131977,Redskins,Nationals,Wizards,Capitals
6,Philadelphia,6070500,Eagles,Phillies,76ers,Flyers
7,Boston,4794447,Patriots,Red Sox,Celtics,Bruins
8,Minneapolis–Saint Paul,3551036,Vikings,Twins,Timberwolves,Wild
9,Denver,2853077,Broncos,Rockies,Nuggets,Avalanche
10,Miami–Fort Lauderdale,6066387,Dolphins,Marlins,Heat,Panthers
11,Phoenix,4661537,Cardinals,Diamondbacks,Suns,Coyotes
12,Detroit,4297617,Lions,Tigers,Pistons,Red Wings
13,Toronto,5928040,—,Blue Jays,Raptors,Maple Leafs
14,Houston,6772470,Texans,Astros,Rockets,—
15,Atlanta,5789700,Falcons,Braves,Hawks,
16,Tampa Bay Area,3032171,Buccaneers,Rays,—,Lightning
17,Pittsburgh,2342299,Steelers,Pirates,,Penguins
18,Cleveland,2055612,Browns,Indians,Cavaliers,
19,Seattle,3798902,Seahawks,Mariners,,
20,Cincinnati,2165139,Bengals,Reds,,—
21,Kansas City,2104509,Chiefs,Royals,,
22,St. Louis,2807002,,Cardinals,,Blues
23,Baltimore,2798886,Ravens,Orioles,,—
24,Charlotte,2474314,Panthers,—,Hornets,—
25,Indianapolis,2004230,Colts,,Pacers,—
26,Nashville,1865298,Titans,—,—,Predators
27,Milwaukee,1572482,,Brewers,Bucks,—
28,New Orleans,1268883,Saints,—,Pelicans,—
29,Buffalo,1132804,Bills,,,Sabres
30,Montreal,4098927,—,,—,Canadiens
31,Vancouver,2463431,—,—,,Canucks
32,Orlando,2441257,—,—,Magic,—
33,Portland,2424955,—,—,Trail Blazers,—
34,Columbus,2041520,—,—,—,Blue Jackets
35,Calgary,1392609,—,—,—,Flames
36,Ottawa,1323783,—,—,—,Senators
37,Edmonton,1321426,—,—,—,Oilers
38,Salt Lake City,1186187,—,—,Jazz,—
39,Winnipeg,778489,—,—,—,Jets
40,San Diego,3317749,,Padres,,—
41,San Antonio,2429609,,—,Spurs,—
42,Sacramento,2296418,—,—,Kings,—
43,Las Vegas,2155664,,—,—,Golden Knights
44,Jacksonville,1478212,Jaguars,—,—,—
45,Oklahoma City,1373211,—,—,Thunder,—
46,Memphis,1342842,,—,Grizzlies,—
47,Raleigh,1302946,—,—,—,Hurricanes
48,Green Bay,318236,Packers,—,—,—
49,Hamilton,747545,—,—,—,
50,Regina,236481,—,—,—,—

separating the teams into new rows.

In [2]:
cities_nhl = cities.copy()[['Metropolitan area', 'NHL', 'Population 2016']]

cities_nhl['NHL'] = cities['NHL'].str.split(' ')


cities_nhl = cities_nhl.explode('NHL')

#cities_nhl.set_index('Metropolitan area', inplace=True)

cities_nhl.replace('—', np.nan, inplace=True)
cities_nhl.replace('', np.nan, inplace=True)

cities_nhl.dropna(inplace=True) #

cities_nhl

         Metropolitan area         NHL Population 2016
0            New York City     Rangers        20153634
0            New York City   Islanders        20153634
0            New York City      Devils        20153634
1              Los Angeles       Kings        13310447
1              Los Angeles       Ducks        13310447
2   San Francisco Bay Area      Sharks         6657982
3                  Chicago  Blackhawks         9512999
4        Dallas–Fort Worth       Stars         7233323
5         Washington, D.C.    Capitals         6131977
6             Philadelphia      Flyers         6070500
7                   Boston      Bruins         4794447
8   Minneapolis–Saint Paul        Wild         3551036
9                   Denver   Avalanche         2853077
10   Miami–Fort Lauderdale    Panthers         6066387
11                 Phoenix     Coyotes         4661537
12                 Detroit         Red         4297617
12                 Detroit       Wings         4297617
13                 Toronto       Maple         5928040
13                 Toronto       Leafs         5928040
16          Tampa Bay Area   Lightning         3032171
17              Pittsburgh    Penguins         2342299
22               St. Louis       Blues         2807002
26               Nashville   Predators         1865298
29                 Buffalo      Sabres         1132804
30                Montreal   Canadiens         4098927
31               Vancouver     Canucks         2463431
34                Columbus        Blue         2041520
34                Columbus     Jackets         2041520
35                 Calgary      Flames         1392609
36                  Ottawa    Senators         1323783
37                Edmonton      Oilers         1321426
39                Winnipeg        Jets          778489
43               Las Vegas      Golden         2155664
43               Las Vegas     Knights         2155664
47                 Raleigh  Hurricanes         1302946

## Note:
Here we see that we have several teams for each region.

In [3]:
nhl_df = nhl_df[nhl_df["year"] == 2018]
nhl_df.head(nhl_df.shape[0])

,team,GP,W,L,OL,PTS,PTS%,GF,GA,SRS,SOS,RPt%,ROW,year,League
0,Atlantic Division,Atlantic Division,Atlantic Division,Atlantic Division,Atlantic Division,Atlantic Division,Atlantic Division,Atlantic Division,Atlantic Division,Atlantic Division,Atlantic Division,Atlantic Division,Atlantic Division,2018,NHL
1,Tampa Bay Lightning*,82,54,23,5,113,.689,296,236,0.66,-0.07,.634,48,2018,NHL
2,Boston Bruins*,82,50,20,12,112,.683,270,214,0.62,-0.07,.610,47,2018,NHL
3,Toronto Maple Leafs*,82,49,26,7,105,.640,277,232,0.49,-0.06,.567,42,2018,NHL
4,Florida Panthers,82,44,30,8,96,.585,248,246,-0.01,-0.04,.537,41,2018,NHL
5,Detroit Red Wings,82,30,39,13,73,.445,217,255,-0.48,-0.01,.341,25,2018,NHL
6,Montreal Canadiens,82,29,40,13,71,.433,209,264,-0.68,0.00,.378,27,2018,NHL
7,Ottawa Senators,82,28,43,11,67,.409,221,291,-0.85,0.00,.372,26,2018,NHL
8,Buffalo Sabres,82,25,45,12,62,.378,199,280,-0.98,0.01,.311,24,2018,NHL
9,Metropolitan Division,Metropolitan Division,Metropolitan Division,Metropolitan Division,Metropolitan Division,Metropolitan Division,Metropolitan Division,Metropolitan Division,Metropolitan Division,Metropolitan Division,Metropolitan Division,Metropolitan Division,Metropolitan Division,2018,NHL
10,Washington Capitals*,82,49,26,7,105,.640,259,239,0.21,-0.04,.585,46,2018,NHL
11,Pittsburgh Penguins*,82,47,29,6,100,.610,272,250,0.23,-0.04,.573,45,2018,NHL
12,Philadelphia Flyers*,82,42,26,14,98,.598,251,243,0.07,-0.03,.543,40,2018,NHL
13,Columbus Blue Jackets*,82,45,30,7,97,.591,242,230,0.11,-0.04,.537,39,2018,NHL
14,New Jersey Devils*,82,44,29,9,97,.591,248,244,0.02,-0.03,.530,39,2018,NHL
15,Carolina Hurricanes,82,36,35,11,83,.506,228,256,-0.35,-0.01,.439,33,2018,NHL
16,New York Islanders,82,35,37,10,80,.488,264,296,-0.40,-0.01,.427,32,2018,NHL
17,New York Rangers,82,34,39,9,77,.470,231,268,-0.46,-0.01,.427,31,2018,NHL
18,Central Division,Central Division,Central Division,Central Division,Central Division,Central Division,Central Division,Central Division,Central Division,Central Division,Central Division,Central Division,Central Division,2018,NHL
19,Nashville Predators*,82,53,18,11,117,.713,267,211,0.71,0.03,.652,47,2018,NHL
20,Winnipeg Jets*,82,52,20,10,114,.695,277,218,0.74,0.02,.622,48,2018,NHL
21,Minnesota Wild*,82,45,26,11,101,.616,253,232,0.29,0.04,.549,42,2018,NHL
22,Colorado Avalanche*,82,43,30,9,95,.579,257,237,0.28,0.04,.518,41,2018,NHL
23,St. Louis Blues,82,44,32,6,94,.573,226,222,0.10,0.05,.518,41,2018,NHL
24,Dallas Stars,82,42,32,8,92,.561,235,225,0.17,0.04,.506,38,2018,NHL
25,Chicago Blackhawks,82,33,39,10,76,.463,229,256,-0.26,0.07,.409,32,2018,NHL
26,Pacific Division,Pacific Division,Pacific Division,Pacific Division,Pacific Division,Pacific Division,Pacific Division,Pacific Division,Pacific Division,Pacific Division,Pacific Division,Pacific Division,Pacific Division,2018,NHL
27,Vegas Golden Knights*,82,51,24,7,109,.665,272,228,0.52,-0.01,.616,47,2018,NHL
28,Anaheim Ducks*,82,44,25,13,101,.616,235,216,0.24,0.01,.555,40,2018,NHL
29,San Jose Sharks*,82,45,27,10,100,.610,252,229,0.28,0.00,.537,40,2018,NHL
30,Los Angeles Kings*,82,45,29,8,98,.598,239,203,0.44,0.00,.543,43,2018,NHL
31,Calgary Flames,82,37,35,10,84,.512,218,248,-0.33,0.03,.470,35,2018,NHL
32,Edmonton Oilers,82,36,40,6,78,.476,234,263,-0.32,0.03,.415,31,2018,NHL
33,Vancouver Canucks,82,31,40,11,73,.445,218,264,-0.51,0.05,.409,31,2018,NHL
34,Arizona Coyotes,82,29,41,12,70,.427,208,256,-0.53,0.05,.372,27,2018,NHL

In [4]:
# dropping the rows specifying the divisions: Atlantic division, Metropolitan division, Central division and Pacific division

nhl_df.drop(axis=0, index = [0, 9, 18, 26], inplace=True)
#nhl_df.reset_index()
nhl_df.replace(to_replace="\*", value = "", regex=True, inplace=True)
nhl_df['team'] = nhl_df['team'].str.split().str[-1]
#cities = cities.replace(to_replace="\[.*?\]", value= "", regex= True )

In [5]:
nhl_df = nhl_df[["team", "W", "L"]]
nhl_df

          team   W   L
1    Lightning  54  23
2       Bruins  50  20
3        Leafs  49  26
4     Panthers  44  30
5        Wings  30  39
6    Canadiens  29  40
7     Senators  28  43
8       Sabres  25  45
10    Capitals  49  26
11    Penguins  47  29
12      Flyers  42  26
13     Jackets  45  30
14      Devils  44  29
15  Hurricanes  36  35
16   Islanders  35  37
17     Rangers  34  39
19   Predators  53  18
20        Jets  52  20
21        Wild  45  26
22   Avalanche  43  30
23       Blues  44  32
24       Stars  42  32
25  Blackhawks  33  39
27     Knights  51  24
28       Ducks  44  25
29      Sharks  45  27
30       Kings  45  29
31      Flames  37  35
32      Oilers  36  40
33     Canucks  31  40
34     Coyotes  29  41

In [6]:
nhl_df["W"] = pd.to_numeric(nhl_df["W"])
nhl_df["L"] = pd.to_numeric(nhl_df["L"])
nhl_df["W/L Ratio"] = nhl_df["W"]/(nhl_df["L"]+nhl_df["W"]) #PTS% is the win ratio?

Now let's join the NHL data with the metropolitan area data, and filter out the metropolitan areas that are not in the NHL data:

In [7]:
nhl_merged = pd.merge(nhl_df, cities_nhl, how='inner', left_on='team', right_on='NHL')
nhl_merged

,team,W,L,W/L Ratio,Metropolitan area,NHL,Population 2016
0,Lightning,54,23,0.701299,Tampa Bay Area,Lightning,3032171
1,Bruins,50,20,0.714286,Boston,Bruins,4794447
2,Leafs,49,26,0.653333,Toronto,Leafs,5928040
3,Panthers,44,30,0.594595,Miami–Fort Lauderdale,Panthers,6066387
4,Wings,30,39,0.434783,Detroit,Wings,4297617
5,Canadiens,29,40,0.420290,Montreal,Canadiens,4098927
6,Senators,28,43,0.394366,Ottawa,Senators,1323783
7,Sabres,25,45,0.357143,Buffalo,Sabres,1132804
8,Capitals,49,26,0.653333,"Washington, D.C.",Capitals,6131977
9,Penguins,47,29,0.618421,Pittsburgh,Penguins,2342299
10,Flyers,42,26,0.617647,Philadelphia,Flyers,6070500
11,Jackets,45,30,0.600000,Columbus,Jackets,2041520
12,Devils,44,29,0.602740,New York City,Devils,20153634
13,Hurricanes,36,35,0.507042,Raleigh,Hurricanes,1302946
14,Islanders,35,37,0.486111,New York City,Islanders,20153634
15,Rangers,34,39,0.465753,New York City,Rangers,20153634
16,Predators,53,18,0.746479,Nashville,Predators,1865298
17,Jets,52,20,0.722222,Winnipeg,Jets,778489
18,Wild,45,26,0.633803,Minneapolis–Saint Paul,Wild,3551036
19,Avalanche,43,30,0.589041,Denver,Avalanche,2853077
20,Blues,44,32,0.578947,St. Louis,Blues,2807002
21,Stars,42,32,0.567568,Dallas–Fort Worth,Stars,7233323
22,Blackhawks,33,39,0.458333,Chicago,Blackhawks,9512999
23,Knights,51,24,0.680000,Las Vegas,Knights,2155664
24,Ducks,44,25,0.637681,Los Angeles,Ducks,13310447
25,Sharks,45,27,0.625000,San Francisco Bay Area,Sharks,6657982
26,Kings,45,29,0.608108,Los Angeles,Kings,13310447
27,Flames,37,35,0.513889,Calgary,Flames,1392609
28,Oilers,36,40,0.473684,Edmonton,Oilers,1321426
29,Canucks,31,40,0.436620,Vancouver,Canucks,2463431
30,Coyotes,29,41,0.414286,Phoenix,Coyotes,4661537

In [8]:
nhl_grouped = nhl_merged.groupby('Metropolitan area').agg({'Population 2016': 'first' , 'W/L Ratio': np.mean})
nhl_grouped.reset_index(inplace=True)
nhl_grouped

         Metropolitan area Population 2016  W/L Ratio
0                   Boston         4794447   0.714286
1                  Buffalo         1132804   0.357143
2                  Calgary         1392609   0.513889
3                  Chicago         9512999   0.458333
4                 Columbus         2041520   0.600000
5        Dallas–Fort Worth         7233323   0.567568
6                   Denver         2853077   0.589041
7                  Detroit         4297617   0.434783
8                 Edmonton         1321426   0.473684
9                Las Vegas         2155664   0.680000
10             Los Angeles        13310447   0.622895
11   Miami–Fort Lauderdale         6066387   0.594595
12  Minneapolis–Saint Paul         3551036   0.633803
13                Montreal         4098927   0.420290
14               Nashville         1865298   0.746479
15           New York City        20153634   0.518201
16                  Ottawa         1323783   0.394366
17            Philadelphia         6070500   0.617647
18                 Phoenix         4661537   0.414286
19              Pittsburgh         2342299   0.618421
20                 Raleigh         1302946   0.507042
21  San Francisco Bay Area         6657982   0.625000
22               St. Louis         2807002   0.578947
23          Tampa Bay Area         3032171   0.701299
24                 Toronto         5928040   0.653333
25               Vancouver         2463431   0.436620
26        Washington, D.C.         6131977   0.653333
27                Winnipeg          778489   0.722222

In [9]:
def nhl_correlation(): 
    
    #1) WORKING OUT THE CITIES DATA
    cities_nhl = cities.copy()[['Metropolitan area', 'NHL', 'Population 2016']] #we gotta create a copy to avoid an error
    
    #separating the teams in a region
    cities_nhl['NHL'] = cities['NHL'].str.split(' ')
    cities_nhl = cities_nhl.explode('NHL')

    #further cleaning the data
    cities_nhl.replace('—', np.nan, inplace=True) #There are data missing for some cities.
    cities_nhl.replace('', np.nan, inplace=True)
    cities_nhl.dropna(inplace=True)

    #2) NHL DATA. WORKING OUT THE DATA FOR THE NATIONAL HOCKEY TEAMS. YEAR 2018
    nhl_df=pd.read_csv("nhl.csv")
    nhl_df = nhl_df[nhl_df["year"] == 2018]
    
    nhl_df.drop(axis=0, index = [0, 9, 18, 26], inplace=True) # dropping the rows specifying the divisions: Atlantic division, Metropolitan division, etc.
    nhl_df.replace(to_replace="\*", value = "", regex=True, inplace=True) #cleaning asterics
    nhl_df['team'] = nhl_df['team'].str.split().str[-1] #selecting the last word that denominates the team's name
    nhl_df = nhl_df[["team", "W", "L"]]
    nhl_df["W"] = pd.to_numeric(nhl_df["W"])
    nhl_df["L"] = pd.to_numeric(nhl_df["L"])
    nhl_df["W/L Ratio"] = nhl_df["W"]/(nhl_df["L"]+nhl_df["W"]) #creaing the W/L Ratio column we need
    
    #3) joining the NHL data with the metropolitan area data, and filtering out the metropolitan areas that are not in the NHL data:
    nhl_merged = pd.merge(nhl_df, cities_nhl, how='inner', left_on='team', right_on='NHL')
    nhl_grouped = nhl_merged.groupby('Metropolitan area').agg({'Population 2016': 'first' , 'W/L Ratio': np.mean})
    nhl_grouped.reset_index(inplace=True) #if we don't do this the cities are gonna be the indexes
    
    
    population_by_region = pd.to_numeric(nhl_grouped['Population 2016']) # pass in metropolitan area population from cities
    win_loss_by_region = nhl_grouped['W/L Ratio'] # pass in win/loss ratio from nhl_df in the same order as cities["Metropolitan area"]

    assert len(population_by_region) == len(win_loss_by_region), "Q1: Your lists must be the same length"
    assert len(population_by_region) == 28, "Q1: There should be 28 teams being analysed for NHL"
    
    return stats.pearsonr(population_by_region, win_loss_by_region)

nhl_correlation()

(0.012486162921209895, 0.9497182859911791)

## Question 2
For this question, calculate the win/loss ratio's correlation with the population of the city it is in for the **NBA** using **2018** data.

In [10]:
import pandas as pd
import numpy as np
import scipy.stats as stats
import re

nba_df=pd.read_csv("nba.csv")
cities=pd.read_html("wikipedia_data.html")[1]
cities=cities.iloc[:-1,[0,3,5,6,7,8]]


cities = cities.replace(to_replace="\(.*?\)", value= "", regex= True )
cities = cities.replace(to_replace="(?<=[a-z])(?=[A-Z])", value=" ", regex=True) #locally I got texts like "GianJets" instead of "Giant Jets" so I added a space between lower and upper case letters

#REMOVING BLANK SPACES FROM THE COLUMNS
cities.columns = cities.columns.str.strip()

cities.rename(columns = {'Population (2016 est.)[8]': 'Population 2016'}, inplace=True)

def nba_correlation():
    
    #1) WORKING OUT THE CITIES DATA
    cities_nba = cities.copy()[['Metropolitan area', 'NBA', 'Population 2016']] #we gotta create a copy to avoid an error
    
    #separating the teams in a region
    cities_nba['NBA'] = cities['NBA'].str.split(' ')
    cities_nba = cities_nba.explode('NBA')

    #further cleaning the data
    cities_nba.replace('—', np.nan, inplace=True) #There are data missing for some cities.
    cities_nba.replace('', np.nan, inplace=True)
    cities_nba.dropna(inplace=True)

    #2) NHL DATA. WORKING OUT THE DATA FOR THE NATIONAL HOCKEY TEAMS. YEAR 2018
    nba_df=pd.read_csv("nba.csv")
    nba_df = nba_df[nba_df["year"] == 2018]
    
    nba_df.drop(axis=0, index = [0, 9, 18, 26], inplace=True) # dropping the rows specifying the divisions: Atlantic division, Metropolitan division, etc.
    nba_df.replace(to_replace="\*", value = "", regex=True, inplace=True) #cleaning asterics
    nba_df['team'] = nba_df['team'].str.split().str[-1] #selecting the last word that denominates the team's name
    nba_df = nba_df[["team", "W", "L"]]
    nba_df["W"] = pd.to_numeric(nba_df["W"])
    nba_df["L"] = pd.to_numeric(nba_df["L"])
    nba_df["W/L Ratio"] = nba_df["W"]/(nba_df["L"]+nba_df["W"]) #creaing the W/L Ratio column we need
    
    #3) joining the NHL data with the metropolitan area data, and filtering out the metropolitan areas that are not in the NHL data:
    nba_merged = pd.merge(nba_df, cities_nba, how='inner', left_on='team', right_on='NBA')
    nba_grouped = nba_merged.groupby('Metropolitan area').agg({'Population 2016': 'first' , 'W/L Ratio': np.mean})
    nba_grouped.reset_index(inplace=True) #if we don't do this the cities are gonna be the indexes
    
    
    population_by_region = pd.to_numeric(nba_grouped['Population 2016']) # pass in metropolitan area population from cities
    win_loss_by_region = nba_grouped['W/L Ratio'] # pass in win/loss ratio from nhl_df in the same order as cities["Metropolitan area"]

    assert len(population_by_region) == len(win_loss_by_region), "Q2: Your lists must be the same length"
    assert len(population_by_region) == 28, "Q2: There should be 28 teams being analysed for NBA"
    
    return stats.pearsonr(population_by_region, win_loss_by_region)

nba_correlation()

AssertionError: Q2: There should be 28 teams being analysed for NBA

In [ ]:
#1) WORKING OUT THE CITIES DATA
cities_nba = cities.copy()[['Metropolitan area', 'NBA', 'Population 2016']] #we gotta create a copy to avoid an error

#separating the teams in a region
cities_nba['NBA'] = cities['NBA'].str.split(' ')
cities_nba = cities_nba.explode('NBA')

#further cleaning the data
cities_nba.replace('—', np.nan, inplace=True) #There are data missing for some cities.
cities_nba.replace('', np.nan, inplace=True)
cities_nba.dropna(inplace=True)

#2) NHL DATA. WORKING OUT THE DATA FOR THE NATIONAL BASKETBALL TEAMS. YEAR 2018
nba_df=pd.read_csv("nba.csv")
nba_df = nba_df[nba_df["year"] == 2018]

#nba_df.drop(axis=0, index = [0, 9, 18, 26], inplace=True) # dropping the rows specifying the divisions: Atlantic division, Metropolitan division, etc.
nba_df.replace(to_replace="\*", value = "", regex=True, inplace=True) #cleaning asterics
nba_df = nba_df.replace(to_replace="\(.*?\)", value= "", regex= True ) #cleaning parenthesis
nba_df['team'] = nba_df['team'].str.split().str[-1] #selecting the last word that denominates the team's name
nba_df = nba_df[["team", "W", "L"]]
nba_df["W"] = pd.to_numeric(nba_df["W"])
nba_df["L"] = pd.to_numeric(nba_df["L"])
nba_df["W/L Ratio"] = nba_df["W"]/(nba_df["L"]+nba_df["W"]) #creaing the W/L Ratio column we need

#3) joining the NHL data with the metropolitan area data, and filtering out the metropolitan areas that are not in the NHL data:
nba_merged = pd.merge(nba_df, cities_nba, how='inner', left_on='team', right_on='NBA')
nba_grouped = nba_merged.groupby('Metropolitan area').agg({'Population 2016': 'first' , 'W/L Ratio': np.mean})
nba_grouped.reset_index(inplace=True) #if we don't do this the cities are gonna be the indexes


population_by_region = pd.to_numeric(nba_grouped['Population 2016']) # pass in metropolitan area population from cities
win_loss_by_region = nba_grouped['W/L Ratio'] # pass in win/loss ratio from nhl_df in the same order as cities["Metropolitan area"]

assert len(population_by_region) == len(win_loss_by_region), "Q2: Your lists must be the same length"
assert len(population_by_region) == 28, "Q2: There should be 28 teams being analysed for NBA"

return stats.pearsonr(population_by_region, win_loss_by_region)

cities_nba

SyntaxError: 'return' outside function (4067922119.py, line 38)

In [11]:
cities=pd.read_html("wikipedia_data.html")[1]
cities=cities.iloc[:-1,[0,3,5,6,7,8]]

cities = cities.replace(to_replace="\[.*?\]", value= "", regex= True )
cities = cities.replace(to_replace="(?<=[a-z])(?=[A-Z])", value=" ", regex=True) #locally I got texts like "GianJets" instead of "Giant Jets" so I added a space between lower and upper case letters

#REMOVING BLANK SPACES FROM THE COLUMNS
cities.columns = cities.columns.str.strip()

cities.rename(columns = {'Population (2016 est.)[8]': 'Population 2016'}, inplace=True)

In [12]:
cities_nba = cities.copy()[['Metropolitan area', 'NBA', 'Population 2016']] #we gotta create a copy to avoid an error

#separating the teams in a region
cities_nba['NBA'] = cities['NBA'].str.split(' ')
cities_nba = cities_nba.explode('NBA')

#further cleaning the data
cities_nba.replace('—', np.nan, inplace=True) #There are data missing for some cities.
cities_nba.replace('', np.nan, inplace=True)
cities_nba.dropna(inplace=True)
cities_nba

         Metropolitan area           NBA Population 2016
0            New York City        Knicks        20153634
0            New York City          Nets        20153634
1              Los Angeles        Lakers        13310447
1              Los Angeles      Clippers        13310447
2   San Francisco Bay Area      Warriors         6657982
3                  Chicago         Bulls         9512999
4        Dallas–Fort Worth     Mavericks         7233323
5         Washington, D.C.       Wizards         6131977
6             Philadelphia         76ers         6070500
7                   Boston       Celtics         4794447
8   Minneapolis–Saint Paul  Timberwolves         3551036
9                   Denver       Nuggets         2853077
10   Miami–Fort Lauderdale          Heat         6066387
11                 Phoenix          Suns         4661537
12                 Detroit       Pistons         4297617
13                 Toronto       Raptors         5928040
14                 Houston       Rockets         6772470
15                 Atlanta         Hawks         5789700
18               Cleveland     Cavaliers         2055612
24               Charlotte       Hornets         2474314
25            Indianapolis        Pacers         2004230
27               Milwaukee         Bucks         1572482
28             New Orleans      Pelicans         1268883
32                 Orlando         Magic         2441257
33                Portland         Trail         2424955
33                Portland       Blazers         2424955
38          Salt Lake City          Jazz         1186187
41             San Antonio         Spurs         2429609
42              Sacramento         Kings         2296418
45           Oklahoma City       Thunder         1373211
46                 Memphis     Grizzlies         1342842

In [13]:
#2) NHL DATA. WORKING OUT THE DATA FOR THE NATIONAL HOCKEY TEAMS. YEAR 2018
nba_df=pd.read_csv("nba.csv")
nba_df = nba_df[nba_df["year"] == 2018]
nba_df.head(nba_df.shape[0])

,team,W,L,W/L%,GB,PS/G,PA/G,SRS,year,League
0,Toronto Raptors* (1),59,23,0.72,—,111.7,103.9,7.29,2018,NBA
1,Boston Celtics* (2),55,27,0.6709999999999999,4.0,104.0,100.4,3.23,2018,NBA
2,Philadelphia 76ers* (3),52,30,0.634,7.0,109.8,105.3,4.3,2018,NBA
3,Cleveland Cavaliers* (4),50,32,0.61,9.0,110.9,109.9,0.59,2018,NBA
4,Indiana Pacers* (5),48,34,0.585,11.0,105.6,104.2,1.18,2018,NBA
5,Miami Heat* (6),44,38,0.537,15.0,103.4,102.9,0.15,2018,NBA
6,Milwaukee Bucks* (7),44,38,0.537,15.0,106.5,106.8,-0.45,2018,NBA
7,Washington Wizards* (8),43,39,0.524,16.0,106.6,106.0,0.53,2018,NBA
8,Detroit Pistons (9),39,43,0.47600000000000003,20.0,103.8,103.9,-0.26,2018,NBA
9,Charlotte Hornets (10),36,46,0.439,23.0,108.2,108.0,0.07,2018,NBA
10,New York Knicks (11),29,53,0.354,30.0,104.5,108.0,-3.53,2018,NBA
11,Brooklyn Nets (12),28,54,0.341,31.0,106.6,110.3,-3.67,2018,NBA
12,Chicago Bulls (13),27,55,0.32899999999999996,32.0,102.9,110.0,-6.84,2018,NBA
13,Orlando Magic (14),25,57,0.305,34.0,103.4,108.2,-4.92,2018,NBA
14,Atlanta Hawks (15),24,58,0.293,35.0,103.4,108.8,-5.3,2018,NBA
15,Houston Rockets* (1),65,17,0.7929999999999999,—,112.4,103.9,8.21,2018,NBA
16,Golden State Warriors* (2),58,24,0.7070000000000001,7.0,113.5,107.5,5.79,2018,NBA
17,Portland Trail Blazers* (3),49,33,0.598,16.0,105.6,103.0,2.6,2018,NBA
18,Oklahoma City Thunder* (4),48,34,0.585,17.0,107.9,104.4,3.42,2018,NBA
19,Utah Jazz* (5),48,34,0.585,17.0,104.1,99.8,4.47,2018,NBA
20,New Orleans Pelicans* (6),48,34,0.585,17.0,111.7,110.4,1.48,2018,NBA
21,San Antonio Spurs* (7),47,35,0.573,18.0,102.7,99.8,2.89,2018,NBA
22,Minnesota Timberwolves* (8),47,35,0.573,18.0,109.5,107.3,2.35,2018,NBA
23,Denver Nuggets (9),46,36,0.561,19.0,110.0,108.5,1.57,2018,NBA
24,Los Angeles Clippers (10),42,40,0.512,23.0,109.0,109.0,0.15,2018,NBA
25,Los Angeles Lakers (11),35,47,0.42700000000000005,30.0,108.1,109.6,-1.44,2018,NBA
26,Sacramento Kings (12),27,55,0.32899999999999996,38.0,98.8,105.8,-6.6,2018,NBA
27,Dallas Mavericks (13),24,58,0.293,41.0,102.3,105.4,-2.7,2018,NBA
28,Memphis Grizzlies (14),22,60,0.268,43.0,99.3,105.5,-5.81,2018,NBA
29,Phoenix Suns (15),21,61,0.256,44.0,103.9,113.3,-8.8,2018,NBA

In [14]:
nba_df.replace(to_replace="\*", value = "", regex=True, inplace=True)
nba_df = nba_df.replace(to_replace="\(.*?\)", value= "", regex= True )
nba_df['team'] = nba_df['team'].str.split().str[-1] #selecting the last word that denominates the team's name
nba_df

,team,W,L,W/L%,GB,PS/G,PA/G,SRS,year,League
0,Raptors,59,23,0.72,—,111.7,103.9,7.29,2018,NBA
1,Celtics,55,27,0.6709999999999999,4.0,104.0,100.4,3.23,2018,NBA
2,76ers,52,30,0.634,7.0,109.8,105.3,4.3,2018,NBA
3,Cavaliers,50,32,0.61,9.0,110.9,109.9,0.59,2018,NBA
4,Pacers,48,34,0.585,11.0,105.6,104.2,1.18,2018,NBA
5,Heat,44,38,0.537,15.0,103.4,102.9,0.15,2018,NBA
6,Bucks,44,38,0.537,15.0,106.5,106.8,-0.45,2018,NBA
7,Wizards,43,39,0.524,16.0,106.6,106.0,0.53,2018,NBA
8,Pistons,39,43,0.47600000000000003,20.0,103.8,103.9,-0.26,2018,NBA
9,Hornets,36,46,0.439,23.0,108.2,108.0,0.07,2018,NBA
10,Knicks,29,53,0.354,30.0,104.5,108.0,-3.53,2018,NBA
11,Nets,28,54,0.341,31.0,106.6,110.3,-3.67,2018,NBA
12,Bulls,27,55,0.32899999999999996,32.0,102.9,110.0,-6.84,2018,NBA
13,Magic,25,57,0.305,34.0,103.4,108.2,-4.92,2018,NBA
14,Hawks,24,58,0.293,35.0,103.4,108.8,-5.3,2018,NBA
15,Rockets,65,17,0.7929999999999999,—,112.4,103.9,8.21,2018,NBA
16,Warriors,58,24,0.7070000000000001,7.0,113.5,107.5,5.79,2018,NBA
17,Blazers,49,33,0.598,16.0,105.6,103.0,2.6,2018,NBA
18,Thunder,48,34,0.585,17.0,107.9,104.4,3.42,2018,NBA
19,Jazz,48,34,0.585,17.0,104.1,99.8,4.47,2018,NBA
20,Pelicans,48,34,0.585,17.0,111.7,110.4,1.48,2018,NBA
21,Spurs,47,35,0.573,18.0,102.7,99.8,2.89,2018,NBA
22,Timberwolves,47,35,0.573,18.0,109.5,107.3,2.35,2018,NBA
23,Nuggets,46,36,0.561,19.0,110.0,108.5,1.57,2018,NBA
24,Clippers,42,40,0.512,23.0,109.0,109.0,0.15,2018,NBA
25,Lakers,35,47,0.42700000000000005,30.0,108.1,109.6,-1.44,2018,NBA
26,Kings,27,55,0.32899999999999996,38.0,98.8,105.8,-6.6,2018,NBA
27,Mavericks,24,58,0.293,41.0,102.3,105.4,-2.7,2018,NBA
28,Grizzlies,22,60,0.268,43.0,99.3,105.5,-5.81,2018,NBA
29,Suns,21,61,0.256,44.0,103.9,113.3,-8.8,2018,NBA

In [15]:
nba_df = nba_df[["team", "W", "L"]]
nba_df["W"] = pd.to_numeric(nba_df["W"])
nba_df["L"] = pd.to_numeric(nba_df["L"])
nba_df["W/L Ratio"] = nba_df["W"]/(nba_df["L"]+nba_df["W"]) #creaing the W/L Ratio column we need. This can be replace by the dataframe own column
nba_df

C:\Users\estef\AppData\Local\Temp\ipykernel_19620\815696126.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  nba_df["W"] = pd.to_numeric(nba_df["W"])
C:\Users\estef\AppData\Local\Temp\ipykernel_19620\815696126.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  nba_df["L"] = pd.to_numeric(nba_df["L"])
C:\Users\estef\AppData\Local\Temp\ipykernel_19620\815696126.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  nba_df["W/L Ratio"] = nba_df["W"]/(nba_df["L"]+nba_df["W"]) #creaing the W/L Ratio column we need. This can be replace by the dataframe own column

            team   W   L  W/L Ratio
0        Raptors  59  23   0.719512
1        Celtics  55  27   0.670732
2          76ers  52  30   0.634146
3      Cavaliers  50  32   0.609756
4         Pacers  48  34   0.585366
5           Heat  44  38   0.536585
6          Bucks  44  38   0.536585
7        Wizards  43  39   0.524390
8        Pistons  39  43   0.475610
9        Hornets  36  46   0.439024
10        Knicks  29  53   0.353659
11          Nets  28  54   0.341463
12         Bulls  27  55   0.329268
13         Magic  25  57   0.304878
14         Hawks  24  58   0.292683
15       Rockets  65  17   0.792683
16      Warriors  58  24   0.707317
17       Blazers  49  33   0.597561
18       Thunder  48  34   0.585366
19          Jazz  48  34   0.585366
20      Pelicans  48  34   0.585366
21         Spurs  47  35   0.573171
22  Timberwolves  47  35   0.573171
23       Nuggets  46  36   0.560976
24      Clippers  42  40   0.512195
25        Lakers  35  47   0.426829
26         Kings  27  55   0.329268
27     Mavericks  24  58   0.292683
28     Grizzlies  22  60   0.268293
29          Suns  21  61   0.256098

In [16]:
#3) joining the NHL data with the metropolitan area data, and filtering out the metropolitan areas that are not in the NHL data:
nba_merged = pd.merge(nba_df, cities_nba, how='inner', left_on='team', right_on='NBA')
nba_merged

,team,W,L,W/L Ratio,Metropolitan area,NBA,Population 2016
0,Raptors,59,23,0.719512,Toronto,Raptors,5928040
1,Celtics,55,27,0.670732,Boston,Celtics,4794447
2,76ers,52,30,0.634146,Philadelphia,76ers,6070500
3,Cavaliers,50,32,0.609756,Cleveland,Cavaliers,2055612
4,Pacers,48,34,0.585366,Indianapolis,Pacers,2004230
5,Heat,44,38,0.536585,Miami–Fort Lauderdale,Heat,6066387
6,Bucks,44,38,0.536585,Milwaukee,Bucks,1572482
7,Wizards,43,39,0.524390,"Washington, D.C.",Wizards,6131977
8,Pistons,39,43,0.475610,Detroit,Pistons,4297617
9,Hornets,36,46,0.439024,Charlotte,Hornets,2474314
10,Knicks,29,53,0.353659,New York City,Knicks,20153634
11,Nets,28,54,0.341463,New York City,Nets,20153634
12,Bulls,27,55,0.329268,Chicago,Bulls,9512999
13,Magic,25,57,0.304878,Orlando,Magic,2441257
14,Hawks,24,58,0.292683,Atlanta,Hawks,5789700
15,Rockets,65,17,0.792683,Houston,Rockets,6772470
16,Warriors,58,24,0.707317,San Francisco Bay Area,Warriors,6657982
17,Blazers,49,33,0.597561,Portland,Blazers,2424955
18,Thunder,48,34,0.585366,Oklahoma City,Thunder,1373211
19,Jazz,48,34,0.585366,Salt Lake City,Jazz,1186187
20,Pelicans,48,34,0.585366,New Orleans,Pelicans,1268883
21,Spurs,47,35,0.573171,San Antonio,Spurs,2429609
22,Timberwolves,47,35,0.573171,Minneapolis–Saint Paul,Timberwolves,3551036
23,Nuggets,46,36,0.560976,Denver,Nuggets,2853077
24,Clippers,42,40,0.512195,Los Angeles,Clippers,13310447
25,Lakers,35,47,0.426829,Los Angeles,Lakers,13310447
26,Kings,27,55,0.329268,Sacramento,Kings,2296418
27,Mavericks,24,58,0.292683,Dallas–Fort Worth,Mavericks,7233323
28,Grizzlies,22,60,0.268293,Memphis,Grizzlies,1342842
29,Suns,21,61,0.256098,Phoenix,Suns,4661537

In [17]:
nba_grouped = nba_merged.groupby('Metropolitan area').agg({'Population 2016': 'first' , 'W/L Ratio': np.mean})
nba_grouped.reset_index(inplace=True) #if we don't do this the cities are gonna be the indexes
nba_grouped

         Metropolitan area Population 2016  W/L Ratio
0                  Atlanta         5789700   0.292683
1                   Boston         4794447   0.670732
2                Charlotte         2474314   0.439024
3                  Chicago         9512999   0.329268
4                Cleveland         2055612   0.609756
5        Dallas–Fort Worth         7233323   0.292683
6                   Denver         2853077   0.560976
7                  Detroit         4297617   0.475610
8                  Houston         6772470   0.792683
9             Indianapolis         2004230   0.585366
10             Los Angeles        13310447   0.469512
11                 Memphis         1342842   0.268293
12   Miami–Fort Lauderdale         6066387   0.536585
13               Milwaukee         1572482   0.536585
14  Minneapolis–Saint Paul         3551036   0.573171
15             New Orleans         1268883   0.585366
16           New York City        20153634   0.347561
17           Oklahoma City         1373211   0.585366
18                 Orlando         2441257   0.304878
19            Philadelphia         6070500   0.634146
20                 Phoenix         4661537   0.256098
21                Portland         2424955   0.597561
22              Sacramento         2296418   0.329268
23          Salt Lake City         1186187   0.585366
24             San Antonio         2429609   0.573171
25  San Francisco Bay Area         6657982   0.707317
26                 Toronto         5928040   0.719512
27        Washington, D.C.         6131977   0.524390

In [19]:
def nba_correlation():
    #1) WORKING OUT THE CITIES DATA
    cities_nba = cities.copy()[['Metropolitan area', 'NBA', 'Population 2016']] #we gotta create a copy to avoid an error

    #separating the teams in a region
    cities_nba['NBA'] = cities['NBA'].str.split(' ')
    cities_nba = cities_nba.explode('NBA')

    #further cleaning the data
    cities_nba.replace('—', np.nan, inplace=True) #There are data missing for some cities.
    cities_nba.replace('', np.nan, inplace=True)
    cities_nba.dropna(inplace=True)
   
    #2) NHL DATA. WORKING OUT THE DATA FOR THE NATIONAL HOCKEY TEAMS. YEAR 2018
    nba_df=pd.read_csv("nba.csv")
    nba_df = nba_df[nba_df["year"] == 2018]
    nba_df.head(nba_df.shape[0])
    nba_df.replace(to_replace="\*", value = "", regex=True, inplace=True)
    nba_df = nba_df.replace(to_replace="\(.*?\)", value= "", regex= True )
    nba_df['team'] = nba_df['team'].str.split().str[-1] #selecting the last word that denominates the team's name
    nba_df = nba_df[["team", "W", "L"]]
    nba_df["W"] = pd.to_numeric(nba_df["W"])
    nba_df["L"] = pd.to_numeric(nba_df["L"])
    nba_df["W/L Ratio"] = nba_df["W"]/(nba_df["L"]+nba_df["W"]) #creaing the W/L Ratio column we need. This can be replace by the dataframe own column
    #3) joining the NHL data with the metropolitan area data, and filtering out the metropolitan areas that are not in the NHL data:
    nba_merged = pd.merge(nba_df, cities_nba, how='inner', left_on='team', right_on='NBA')
    nba_grouped = nba_merged.groupby('Metropolitan area').agg({'Population 2016': 'first' , 'W/L Ratio': np.mean})
    nba_grouped.reset_index(inplace=True) #if we don't do this the cities are gonna be the indexes


    population_by_region = pd.to_numeric(nba_grouped['Population 2016']) # pass in metropolitan area population from cities
    win_loss_by_region = nba_grouped["W/L Ratio"] # pass in win/loss ratio from nba_df in the same order as cities["Metropolitan area"]

    assert len(population_by_region) == len(win_loss_by_region), "Q2: Your lists must be the same length"
    assert len(population_by_region) == 28, "Q2: There should be 28 teams being analysed for NBA"

    return stats.pearsonr(population_by_region, win_loss_by_region)

nba_correlation()

(-0.17657160252844611, 0.3687474160446298)

## Question 3
For this question, calculate the win/loss ratio's correlation with the population of the city it is in for the **MLB** using **2018** data.

In [ ]:
import pandas as pd
import numpy as np
import scipy.stats as stats
import re

mlb_df=pd.read_csv("assets/mlb.csv")
cities=pd.read_html("assets/wikipedia_data.html")[1]
cities=cities.iloc[:-1,[0,3,5,6,7,8]]

def mlb_correlation(): 
    # YOUR CODE HERE
    raise NotImplementedError()
    
    population_by_region = [] # pass in metropolitan area population from cities
    win_loss_by_region = [] # pass in win/loss ratio from mlb_df in the same order as cities["Metropolitan area"]

    assert len(population_by_region) == len(win_loss_by_region), "Q3: Your lists must be the same length"
    assert len(population_by_region) == 26, "Q3: There should be 26 teams being analysed for MLB"

    return stats.pearsonr(population_by_region, win_loss_by_region)

## Question 4
For this question, calculate the win/loss ratio's correlation with the population of the city it is in for the **NFL** using **2018** data.

In [ ]:
import pandas as pd
import numpy as np
import scipy.stats as stats
import re

nfl_df=pd.read_csv("assets/nfl.csv")
cities=pd.read_html("assets/wikipedia_data.html")[1]
cities=cities.iloc[:-1,[0,3,5,6,7,8]]

def nfl_correlation(): 
    # YOUR CODE HERE
    raise NotImplementedError()
    
    population_by_region = [] # pass in metropolitan area population from cities
    win_loss_by_region = [] # pass in win/loss ratio from nfl_df in the same order as cities["Metropolitan area"]

    assert len(population_by_region) == len(win_loss_by_region), "Q4: Your lists must be the same length"
    assert len(population_by_region) == 29, "Q4: There should be 29 teams being analysed for NFL"

    return stats.pearsonr(population_by_region, win_loss_by_region)

## Question 5
In this question I would like you to explore the hypothesis that **given that an area has two sports teams in different sports, those teams will perform the same within their respective sports**. How I would like to see this explored is with a series of paired t-tests (so use [`ttest_rel`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.ttest_rel.html)) between all pairs of sports. Are there any sports where we can reject the null hypothesis? Again, average values where a sport has multiple teams in one region. Remember, you will only be including, for each sport, cities which have teams engaged in that sport, drop others as appropriate. This question is worth 20% of the grade for this assignment.

In [ ]:
import pandas as pd
import numpy as np
import scipy.stats as stats
import re

mlb_df=pd.read_csv("assets/mlb.csv")
nhl_df=pd.read_csv("assets/nhl.csv")
nba_df=pd.read_csv("assets/nba.csv")
nfl_df=pd.read_csv("assets/nfl.csv")
cities=pd.read_html("assets/wikipedia_data.html")[1]
cities=cities.iloc[:-1,[0,3,5,6,7,8]]

def sports_team_performance():
    # YOUR CODE HERE
    raise NotImplementedError()
    
    # Note: p_values is a full dataframe, so df.loc["NFL","NBA"] should be the same as df.loc["NBA","NFL"] and
    # df.loc["NFL","NFL"] should return np.nan
    sports = ['NFL', 'NBA', 'NHL', 'MLB']
    p_values = pd.DataFrame({k:np.nan for k in sports}, index=sports)
    
    assert abs(p_values.loc["NBA", "NHL"] - 0.02) <= 1e-2, "The NBA-NHL p-value should be around 0.02"
    assert abs(p_values.loc["MLB", "NFL"] - 0.80) <= 1e-2, "The MLB-NFL p-value should be around 0.80"
    return p_values