# Assignment 4
## Description
In this assignment you must read in a file of metropolitan regions and associated sports teams from [assets/wikipedia_data.html](assets/wikipedia_data.html) and answer some questions about each metropolitan region. Each of these regions may have one or more teams from the "Big 4": NFL (football, in [assets/nfl.csv](assets/nfl.csv)), MLB (baseball, in [assets/mlb.csv](assets/mlb.csv)), NBA (basketball, in [assets/nba.csv](assets/nba.csv) or NHL (hockey, in [assets/nhl.csv](assets/nhl.csv)). Please keep in mind that all questions are from the perspective of the metropolitan region, and that this file is the "source of authority" for the location of a given sports team. Thus teams which are commonly known by a different area (e.g. "Oakland Raiders") need to be mapped into the metropolitan region given (e.g. San Francisco Bay Area). This will require some human data understanding outside of the data you've been given (e.g. you will have to hand-code some names, and might need to google to find out where teams are)!

For each sport I would like you to answer the question: **what is the win/loss ratio's correlation with the population of the city it is in?** Win/Loss ratio refers to the number of wins over the number of wins plus the number of losses. Remember that to calculate the correlation with [`pearsonr`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.pearsonr.html), so you are going to send in two ordered lists of values, the populations from the wikipedia_data.html file and the win/loss ratio for a given sport in the same order. Average the win/loss ratios for those cities which have multiple teams of a single sport. Each sport is worth an equal amount in this assignment (20%\*4=80%) of the grade for this assignment. You should only use data **from year 2018** for your analysis -- this is important!

## Notes

1. Do not include data about the MLS or CFL in any of the work you are doing, we're only interested in the Big 4 in this assignment.
2. I highly suggest that you first tackle the four correlation questions in order, as they are all similar and worth the majority of grades for this assignment. This is by design!
3. It's fair game to talk with peers about high level strategy as well as the relationship between metropolitan areas and sports teams. However, do not post code solving aspects of the assignment (including such as dictionaries mapping areas to teams, or regexes which will clean up names).
4. There may be more teams than the assert statements test, remember to collapse multiple teams in one city into a single value!

As this assignment utilizes global variables in the skeleton code, to avoid having errors in your code you can either:

1. You can place all of your code within the function definitions for all of the questions (other than import statements).
2. You can create copies of all the global variables with the copy() method and proceed as usual.

## Question 1
For this question, calculate the win/loss ratio's correlation with the population of the city it is in for the **NHL** using **2018** data.

In [1]:
import pandas as pd
import numpy as np
import scipy.stats as stats
import re

nhl_df=pd.read_csv("nhl.csv")
cities=pd.read_html("wikipedia_data.html")[1]
cities=cities.iloc[:-1,[0,3,5,6,7,8]]

cities = cities.replace(to_replace="\[.*?\]", value= "", regex= True )
cities = cities.replace(to_replace="(?<=[a-z])(?=[A-Z])", value=" ", regex=True) #locally I got texts like "GianJets" instead of "Giant Jets" so I added a space between lower and upper case letters

#REMOVING BLANK SPACES FROM THE COLUMNS
cities.columns = cities.columns.str.strip()

cities.rename(columns = {'Population (2016 est.)[8]': 'Population 2016'}, inplace=True)

def nhl_correlation(): 
    # YOUR CODE HERE
    raise NotImplementedError()
    
    population_by_region = [] # pass in metropolitan area population from cities
    win_loss_by_region = [] # pass in win/loss ratio from nhl_df in the same order as cities["Metropolitan area"]

    assert len(population_by_region) == len(win_loss_by_region), "Q1: Your lists must be the same length"
    assert len(population_by_region) == 28, "Q1: There should be 28 teams being analysed for NHL"
    
    return stats.pearsonr(population_by_region, win_loss_by_region)

cities#.iloc[2]["MLB"]

,Metropolitan area,Population 2016,NFL,MLB,NBA,NHL
0,New York City,20153634,Giants Jets,Yankees Mets,Knicks Nets,Rangers Islanders Devils
1,Los Angeles,13310447,Rams Chargers,Dodgers Angels,Lakers Clippers,Kings Ducks
2,San Francisco Bay Area,6657982,49ers Raiders,Giants Athletics,Warriors,Sharks
3,Chicago,9512999,Bears,Cubs White Sox,Bulls,Blackhawks
4,Dallas–Fort Worth,7233323,Cowboys,Rangers,Mavericks,Stars
5,"Washington, D.C.",6131977,Redskins,Nationals,Wizards,Capitals
6,Philadelphia,6070500,Eagles,Phillies,76ers,Flyers
7,Boston,4794447,Patriots,Red Sox,Celtics,Bruins
8,Minneapolis–Saint Paul,3551036,Vikings,Twins,Timberwolves,Wild
9,Denver,2853077,Broncos,Rockies,Nuggets,Avalanche
10,Miami–Fort Lauderdale,6066387,Dolphins,Marlins,Heat,Panthers
11,Phoenix,4661537,Cardinals,Diamondbacks,Suns,Coyotes
12,Detroit,4297617,Lions,Tigers,Pistons,Red Wings
13,Toronto,5928040,—,Blue Jays,Raptors,Maple Leafs
14,Houston,6772470,Texans,Astros,Rockets,—
15,Atlanta,5789700,Falcons,Braves,Hawks,
16,Tampa Bay Area,3032171,Buccaneers,Rays,—,Lightning
17,Pittsburgh,2342299,Steelers,Pirates,,Penguins
18,Cleveland,2055612,Browns,Indians,Cavaliers,
19,Seattle,3798902,Seahawks,Mariners,,
20,Cincinnati,2165139,Bengals,Reds,,—
21,Kansas City,2104509,Chiefs,Royals,,
22,St. Louis,2807002,,Cardinals,,Blues
23,Baltimore,2798886,Ravens,Orioles,,—
24,Charlotte,2474314,Panthers,—,Hornets,—
25,Indianapolis,2004230,Colts,,Pacers,—
26,Nashville,1865298,Titans,—,—,Predators
27,Milwaukee,1572482,,Brewers,Bucks,—
28,New Orleans,1268883,Saints,—,Pelicans,—
29,Buffalo,1132804,Bills,,,Sabres
30,Montreal,4098927,—,,—,Canadiens
31,Vancouver,2463431,—,—,,Canucks
32,Orlando,2441257,—,—,Magic,—
33,Portland,2424955,—,—,Trail Blazers,—
34,Columbus,2041520,—,—,—,Blue Jackets
35,Calgary,1392609,—,—,—,Flames
36,Ottawa,1323783,—,—,—,Senators
37,Edmonton,1321426,—,—,—,Oilers
38,Salt Lake City,1186187,—,—,Jazz,—
39,Winnipeg,778489,—,—,—,Jets
40,San Diego,3317749,,Padres,,—
41,San Antonio,2429609,,—,Spurs,—
42,Sacramento,2296418,—,—,Kings,—
43,Las Vegas,2155664,,—,—,Golden Knights
44,Jacksonville,1478212,Jaguars,—,—,—
45,Oklahoma City,1373211,—,—,Thunder,—
46,Memphis,1342842,,—,Grizzlies,—
47,Raleigh,1302946,—,—,—,Hurricanes
48,Green Bay,318236,Packers,—,—,—
49,Hamilton,747545,—,—,—,
50,Regina,236481,—,—,—,—

separating the teams into new rows.

In [2]:
cities_nhl = cities.copy()[['Metropolitan area', 'NHL', 'Population 2016']]

cities_nhl['NHL'] = cities['NHL'].str.split(' ')


cities_nhl = cities_nhl.explode('NHL')

#cities_nhl.set_index('Metropolitan area', inplace=True)

cities_nhl.replace('—', np.nan, inplace=True)
cities_nhl.replace('', np.nan, inplace=True)

cities_nhl.dropna(inplace=True) #

cities_nhl

         Metropolitan area         NHL Population 2016
0            New York City     Rangers        20153634
0            New York City   Islanders        20153634
0            New York City      Devils        20153634
1              Los Angeles       Kings        13310447
1              Los Angeles       Ducks        13310447
2   San Francisco Bay Area      Sharks         6657982
3                  Chicago  Blackhawks         9512999
4        Dallas–Fort Worth       Stars         7233323
5         Washington, D.C.    Capitals         6131977
6             Philadelphia      Flyers         6070500
7                   Boston      Bruins         4794447
8   Minneapolis–Saint Paul        Wild         3551036
9                   Denver   Avalanche         2853077
10   Miami–Fort Lauderdale    Panthers         6066387
11                 Phoenix     Coyotes         4661537
12                 Detroit         Red         4297617
12                 Detroit       Wings         4297617
13                 Toronto       Maple         5928040
13                 Toronto       Leafs         5928040
16          Tampa Bay Area   Lightning         3032171
17              Pittsburgh    Penguins         2342299
22               St. Louis       Blues         2807002
26               Nashville   Predators         1865298
29                 Buffalo      Sabres         1132804
30                Montreal   Canadiens         4098927
31               Vancouver     Canucks         2463431
34                Columbus        Blue         2041520
34                Columbus     Jackets         2041520
35                 Calgary      Flames         1392609
36                  Ottawa    Senators         1323783
37                Edmonton      Oilers         1321426
39                Winnipeg        Jets          778489
43               Las Vegas      Golden         2155664
43               Las Vegas     Knights         2155664
47                 Raleigh  Hurricanes         1302946

## Note:
Here we see that we have several teams for each region.

In [3]:
nhl_df = nhl_df[nhl_df["year"] == 2018]
nhl_df.head(nhl_df.shape[0])

,team,GP,W,L,OL,PTS,PTS%,GF,GA,SRS,SOS,RPt%,ROW,year,League
0,Atlantic Division,Atlantic Division,Atlantic Division,Atlantic Division,Atlantic Division,Atlantic Division,Atlantic Division,Atlantic Division,Atlantic Division,Atlantic Division,Atlantic Division,Atlantic Division,Atlantic Division,2018,NHL
1,Tampa Bay Lightning*,82,54,23,5,113,.689,296,236,0.66,-0.07,.634,48,2018,NHL
2,Boston Bruins*,82,50,20,12,112,.683,270,214,0.62,-0.07,.610,47,2018,NHL
3,Toronto Maple Leafs*,82,49,26,7,105,.640,277,232,0.49,-0.06,.567,42,2018,NHL
4,Florida Panthers,82,44,30,8,96,.585,248,246,-0.01,-0.04,.537,41,2018,NHL
5,Detroit Red Wings,82,30,39,13,73,.445,217,255,-0.48,-0.01,.341,25,2018,NHL
6,Montreal Canadiens,82,29,40,13,71,.433,209,264,-0.68,0.00,.378,27,2018,NHL
7,Ottawa Senators,82,28,43,11,67,.409,221,291,-0.85,0.00,.372,26,2018,NHL
8,Buffalo Sabres,82,25,45,12,62,.378,199,280,-0.98,0.01,.311,24,2018,NHL
9,Metropolitan Division,Metropolitan Division,Metropolitan Division,Metropolitan Division,Metropolitan Division,Metropolitan Division,Metropolitan Division,Metropolitan Division,Metropolitan Division,Metropolitan Division,Metropolitan Division,Metropolitan Division,Metropolitan Division,2018,NHL
10,Washington Capitals*,82,49,26,7,105,.640,259,239,0.21,-0.04,.585,46,2018,NHL
11,Pittsburgh Penguins*,82,47,29,6,100,.610,272,250,0.23,-0.04,.573,45,2018,NHL
12,Philadelphia Flyers*,82,42,26,14,98,.598,251,243,0.07,-0.03,.543,40,2018,NHL
13,Columbus Blue Jackets*,82,45,30,7,97,.591,242,230,0.11,-0.04,.537,39,2018,NHL
14,New Jersey Devils*,82,44,29,9,97,.591,248,244,0.02,-0.03,.530,39,2018,NHL
15,Carolina Hurricanes,82,36,35,11,83,.506,228,256,-0.35,-0.01,.439,33,2018,NHL
16,New York Islanders,82,35,37,10,80,.488,264,296,-0.40,-0.01,.427,32,2018,NHL
17,New York Rangers,82,34,39,9,77,.470,231,268,-0.46,-0.01,.427,31,2018,NHL
18,Central Division,Central Division,Central Division,Central Division,Central Division,Central Division,Central Division,Central Division,Central Division,Central Division,Central Division,Central Division,Central Division,2018,NHL
19,Nashville Predators*,82,53,18,11,117,.713,267,211,0.71,0.03,.652,47,2018,NHL
20,Winnipeg Jets*,82,52,20,10,114,.695,277,218,0.74,0.02,.622,48,2018,NHL
21,Minnesota Wild*,82,45,26,11,101,.616,253,232,0.29,0.04,.549,42,2018,NHL
22,Colorado Avalanche*,82,43,30,9,95,.579,257,237,0.28,0.04,.518,41,2018,NHL
23,St. Louis Blues,82,44,32,6,94,.573,226,222,0.10,0.05,.518,41,2018,NHL
24,Dallas Stars,82,42,32,8,92,.561,235,225,0.17,0.04,.506,38,2018,NHL
25,Chicago Blackhawks,82,33,39,10,76,.463,229,256,-0.26,0.07,.409,32,2018,NHL
26,Pacific Division,Pacific Division,Pacific Division,Pacific Division,Pacific Division,Pacific Division,Pacific Division,Pacific Division,Pacific Division,Pacific Division,Pacific Division,Pacific Division,Pacific Division,2018,NHL
27,Vegas Golden Knights*,82,51,24,7,109,.665,272,228,0.52,-0.01,.616,47,2018,NHL
28,Anaheim Ducks*,82,44,25,13,101,.616,235,216,0.24,0.01,.555,40,2018,NHL
29,San Jose Sharks*,82,45,27,10,100,.610,252,229,0.28,0.00,.537,40,2018,NHL
30,Los Angeles Kings*,82,45,29,8,98,.598,239,203,0.44,0.00,.543,43,2018,NHL
31,Calgary Flames,82,37,35,10,84,.512,218,248,-0.33,0.03,.470,35,2018,NHL
32,Edmonton Oilers,82,36,40,6,78,.476,234,263,-0.32,0.03,.415,31,2018,NHL
33,Vancouver Canucks,82,31,40,11,73,.445,218,264,-0.51,0.05,.409,31,2018,NHL
34,Arizona Coyotes,82,29,41,12,70,.427,208,256,-0.53,0.05,.372,27,2018,NHL

In [4]:
# dropping the rows specifying the divisions: Atlantic division, Metropolitan division, Central division and Pacific division

nhl_df.drop(axis=0, index = [0, 9, 18, 26], inplace=True)
#nhl_df.reset_index()
nhl_df.replace(to_replace="\*", value = "", regex=True, inplace=True)
nhl_df['team'] = nhl_df['team'].str.split().str[-1]
#cities = cities.replace(to_replace="\[.*?\]", value= "", regex= True )

In [5]:
nhl_df = nhl_df[["team", "W", "L"]]
nhl_df

          team   W   L
1    Lightning  54  23
2       Bruins  50  20
3        Leafs  49  26
4     Panthers  44  30
5        Wings  30  39
6    Canadiens  29  40
7     Senators  28  43
8       Sabres  25  45
10    Capitals  49  26
11    Penguins  47  29
12      Flyers  42  26
13     Jackets  45  30
14      Devils  44  29
15  Hurricanes  36  35
16   Islanders  35  37
17     Rangers  34  39
19   Predators  53  18
20        Jets  52  20
21        Wild  45  26
22   Avalanche  43  30
23       Blues  44  32
24       Stars  42  32
25  Blackhawks  33  39
27     Knights  51  24
28       Ducks  44  25
29      Sharks  45  27
30       Kings  45  29
31      Flames  37  35
32      Oilers  36  40
33     Canucks  31  40
34     Coyotes  29  41

In [6]:
nhl_df["W"] = pd.to_numeric(nhl_df["W"])
nhl_df["L"] = pd.to_numeric(nhl_df["L"])
nhl_df["W/L Ratio"] = nhl_df["W"]/(nhl_df["L"]+nhl_df["W"]) #PTS% is the win ratio?

Now let's join the NHL data with the metropolitan area data, and filter out the metropolitan areas that are not in the NHL data:

In [7]:
nhl_merged = pd.merge(nhl_df, cities_nhl, how='inner', left_on='team', right_on='NHL')
nhl_merged

,team,W,L,W/L Ratio,Metropolitan area,NHL,Population 2016
0,Lightning,54,23,0.701299,Tampa Bay Area,Lightning,3032171
1,Bruins,50,20,0.714286,Boston,Bruins,4794447
2,Leafs,49,26,0.653333,Toronto,Leafs,5928040
3,Panthers,44,30,0.594595,Miami–Fort Lauderdale,Panthers,6066387
4,Wings,30,39,0.434783,Detroit,Wings,4297617
5,Canadiens,29,40,0.420290,Montreal,Canadiens,4098927
6,Senators,28,43,0.394366,Ottawa,Senators,1323783
7,Sabres,25,45,0.357143,Buffalo,Sabres,1132804
8,Capitals,49,26,0.653333,"Washington, D.C.",Capitals,6131977
9,Penguins,47,29,0.618421,Pittsburgh,Penguins,2342299
10,Flyers,42,26,0.617647,Philadelphia,Flyers,6070500
11,Jackets,45,30,0.600000,Columbus,Jackets,2041520
12,Devils,44,29,0.602740,New York City,Devils,20153634
13,Hurricanes,36,35,0.507042,Raleigh,Hurricanes,1302946
14,Islanders,35,37,0.486111,New York City,Islanders,20153634
15,Rangers,34,39,0.465753,New York City,Rangers,20153634
16,Predators,53,18,0.746479,Nashville,Predators,1865298
17,Jets,52,20,0.722222,Winnipeg,Jets,778489
18,Wild,45,26,0.633803,Minneapolis–Saint Paul,Wild,3551036
19,Avalanche,43,30,0.589041,Denver,Avalanche,2853077
20,Blues,44,32,0.578947,St. Louis,Blues,2807002
21,Stars,42,32,0.567568,Dallas–Fort Worth,Stars,7233323
22,Blackhawks,33,39,0.458333,Chicago,Blackhawks,9512999
23,Knights,51,24,0.680000,Las Vegas,Knights,2155664
24,Ducks,44,25,0.637681,Los Angeles,Ducks,13310447
25,Sharks,45,27,0.625000,San Francisco Bay Area,Sharks,6657982
26,Kings,45,29,0.608108,Los Angeles,Kings,13310447
27,Flames,37,35,0.513889,Calgary,Flames,1392609
28,Oilers,36,40,0.473684,Edmonton,Oilers,1321426
29,Canucks,31,40,0.436620,Vancouver,Canucks,2463431
30,Coyotes,29,41,0.414286,Phoenix,Coyotes,4661537

In [8]:
nhl_grouped = nhl_merged.groupby('Metropolitan area').agg({'Population 2016': 'first' , 'W/L Ratio': np.mean})
nhl_grouped.reset_index(inplace=True)
nhl_grouped

         Metropolitan area Population 2016  W/L Ratio
0                   Boston         4794447   0.714286
1                  Buffalo         1132804   0.357143
2                  Calgary         1392609   0.513889
3                  Chicago         9512999   0.458333
4                 Columbus         2041520   0.600000
5        Dallas–Fort Worth         7233323   0.567568
6                   Denver         2853077   0.589041
7                  Detroit         4297617   0.434783
8                 Edmonton         1321426   0.473684
9                Las Vegas         2155664   0.680000
10             Los Angeles        13310447   0.622895
11   Miami–Fort Lauderdale         6066387   0.594595
12  Minneapolis–Saint Paul         3551036   0.633803
13                Montreal         4098927   0.420290
14               Nashville         1865298   0.746479
15           New York City        20153634   0.518201
16                  Ottawa         1323783   0.394366
17            Philadelphia         6070500   0.617647
18                 Phoenix         4661537   0.414286
19              Pittsburgh         2342299   0.618421
20                 Raleigh         1302946   0.507042
21  San Francisco Bay Area         6657982   0.625000
22               St. Louis         2807002   0.578947
23          Tampa Bay Area         3032171   0.701299
24                 Toronto         5928040   0.653333
25               Vancouver         2463431   0.436620
26        Washington, D.C.         6131977   0.653333
27                Winnipeg          778489   0.722222

In [41]:
def nhl_correlation(): 
    
    #1) WORKING OUT THE CITIES DATA
    cities_nhl = cities.copy()[['Metropolitan area', 'NHL', 'Population 2016']] #we gotta create a copy to avoid an error
    
    #separating the teams in a region
    cities_nhl['NHL'] = cities_nhl['NHL'].str.split(' ')
    cities_nhl = cities_nhl.explode('NHL')

    #further cleaning the data
    cities_nhl.replace('—', np.nan, inplace=True) #There are data missing for some cities.
    cities_nhl.replace('', np.nan, inplace=True)
    cities_nhl.dropna(inplace=True)

    #2) NHL DATA. WORKING OUT THE DATA FOR THE NATIONAL HOCKEY TEAMS. YEAR 2018
    nhl_df=pd.read_csv("nhl.csv")
    nhl_df = nhl_df[nhl_df["year"] == 2018]
    
    nhl_df.drop(axis=0, index = [0, 9, 18, 26], inplace=True) # dropping the rows specifying the divisions: Atlantic division, Metropolitan division, etc.
    nhl_df.replace(to_replace="\*", value = "", regex=True, inplace=True) #cleaning asterics
    nhl_df['team'] = nhl_df['team'].str.split().str[-1] #selecting the last word that denominates the team's name
    nhl_df = nhl_df[["team", "W", "L"]]
    nhl_df["W"] = pd.to_numeric(nhl_df["W"])
    nhl_df["L"] = pd.to_numeric(nhl_df["L"])
    nhl_df["W/L Ratio"] = nhl_df["W"]/(nhl_df["L"]+nhl_df["W"]) #creaing the W/L Ratio column we need
    
    #3) joining the NHL data with the metropolitan area data, and filtering out the metropolitan areas that are not in the NHL data:
    nhl_merged = pd.merge(nhl_df, cities_nhl, how='inner', left_on='team', right_on='NHL')
    nhl_grouped = nhl_merged.groupby('Metropolitan area').agg({'Population 2016': 'first' , 'W/L Ratio': np.mean})
    nhl_grouped.reset_index(inplace=True) #if we don't do this the cities are gonna be the indexes
    
    
    population_by_region = pd.to_numeric(nhl_grouped['Population 2016']) # pass in metropolitan area population from cities
    win_loss_by_region = nhl_grouped['W/L Ratio'] # pass in win/loss ratio from nhl_df in the same order as cities["Metropolitan area"]

    assert len(population_by_region) == len(win_loss_by_region), "Q1: Your lists must be the same length"
    assert len(population_by_region) == 28, "Q1: There should be 28 teams being analysed for NHL"
    
    return stats.pearsonr(population_by_region, win_loss_by_region)

nhl_correlation()

(0.012486162921209895, 0.9497182859911791)

## Question 2
For this question, calculate the win/loss ratio's correlation with the population of the city it is in for the **NBA** using **2018** data.

In [10]:
import pandas as pd
import numpy as np
import scipy.stats as stats
import re

nba_df=pd.read_csv("nba.csv")
cities=pd.read_html("wikipedia_data.html")[1]
cities=cities.iloc[:-1,[0,3,5,6,7,8]]


cities = cities.replace(to_replace="\(.*?\)", value= "", regex= True )
cities = cities.replace(to_replace="(?<=[a-z])(?=[A-Z])", value=" ", regex=True) #locally I got texts like "GianJets" instead of "Giant Jets" so I added a space between lower and upper case letters

#REMOVING BLANK SPACES FROM THE COLUMNS
cities.columns = cities.columns.str.strip()

cities.rename(columns = {'Population (2016 est.)[8]': 'Population 2016'}, inplace=True)

def nba_correlation():
    
    #1) WORKING OUT THE CITIES DATA
    cities_nba = cities.copy()[['Metropolitan area', 'NBA', 'Population 2016']] #we gotta create a copy to avoid an error
    
    #separating the teams in a region
    cities_nba['NBA'] = cities['NBA'].str.split(' ')
    cities_nba = cities_nba.explode('NBA')

    #further cleaning the data
    cities_nba.replace('—', np.nan, inplace=True) #There are data missing for some cities.
    cities_nba.replace('', np.nan, inplace=True)
    cities_nba.dropna(inplace=True)

    #2) NHL DATA. WORKING OUT THE DATA FOR THE NATIONAL HOCKEY TEAMS. YEAR 2018
    nba_df=pd.read_csv("nba.csv")
    nba_df = nba_df[nba_df["year"] == 2018]
    
    nba_df.drop(axis=0, index = [0, 9, 18, 26], inplace=True) # dropping the rows specifying the divisions: Atlantic division, Metropolitan division, etc.
    nba_df.replace(to_replace="\*", value = "", regex=True, inplace=True) #cleaning asterics
    nba_df['team'] = nba_df['team'].str.split().str[-1] #selecting the last word that denominates the team's name
    nba_df = nba_df[["team", "W", "L"]]
    nba_df["W"] = pd.to_numeric(nba_df["W"])
    nba_df["L"] = pd.to_numeric(nba_df["L"])
    nba_df["W/L Ratio"] = nba_df["W"]/(nba_df["L"]+nba_df["W"]) #creaing the W/L Ratio column we need
    
    #3) joining the NHL data with the metropolitan area data, and filtering out the metropolitan areas that are not in the NHL data:
    nba_merged = pd.merge(nba_df, cities_nba, how='inner', left_on='team', right_on='NBA')
    nba_grouped = nba_merged.groupby('Metropolitan area').agg({'Population 2016': 'first' , 'W/L Ratio': np.mean})
    nba_grouped.reset_index(inplace=True) #if we don't do this the cities are gonna be the indexes
    
    
    population_by_region = pd.to_numeric(nba_grouped['Population 2016']) # pass in metropolitan area population from cities
    win_loss_by_region = nba_grouped['W/L Ratio'] # pass in win/loss ratio from nhl_df in the same order as cities["Metropolitan area"]

    assert len(population_by_region) == len(win_loss_by_region), "Q2: Your lists must be the same length"
    assert len(population_by_region) == 28, "Q2: There should be 28 teams being analysed for NBA"
    
    return stats.pearsonr(population_by_region, win_loss_by_region)

nba_correlation()

AssertionError: Q2: There should be 28 teams being analysed for NBA

In [ ]:
#1) WORKING OUT THE CITIES DATA
cities_nba = cities.copy()[['Metropolitan area', 'NBA', 'Population 2016']] #we gotta create a copy to avoid an error

#separating the teams in a region
cities_nba['NBA'] = cities['NBA'].str.split(' ')
cities_nba = cities_nba.explode('NBA')

#further cleaning the data
cities_nba.replace('—', np.nan, inplace=True) #There are data missing for some cities.
cities_nba.replace('', np.nan, inplace=True)
cities_nba.dropna(inplace=True)

#2) NHL DATA. WORKING OUT THE DATA FOR THE NATIONAL BASKETBALL TEAMS. YEAR 2018
nba_df=pd.read_csv("nba.csv")
nba_df = nba_df[nba_df["year"] == 2018]

#nba_df.drop(axis=0, index = [0, 9, 18, 26], inplace=True) # dropping the rows specifying the divisions: Atlantic division, Metropolitan division, etc.
nba_df.replace(to_replace="\*", value = "", regex=True, inplace=True) #cleaning asterics
nba_df = nba_df.replace(to_replace="\(.*?\)", value= "", regex= True ) #cleaning parenthesis
nba_df['team'] = nba_df['team'].str.split().str[-1] #selecting the last word that denominates the team's name
nba_df = nba_df[["team", "W", "L"]]
nba_df["W"] = pd.to_numeric(nba_df["W"])
nba_df["L"] = pd.to_numeric(nba_df["L"])
nba_df["W/L Ratio"] = nba_df["W"]/(nba_df["L"]+nba_df["W"]) #creaing the W/L Ratio column we need

#3) joining the NHL data with the metropolitan area data, and filtering out the metropolitan areas that are not in the NHL data:
nba_merged = pd.merge(nba_df, cities_nba, how='inner', left_on='team', right_on='NBA')
nba_grouped = nba_merged.groupby('Metropolitan area').agg({'Population 2016': 'first' , 'W/L Ratio': np.mean})
nba_grouped.reset_index(inplace=True) #if we don't do this the cities are gonna be the indexes


population_by_region = pd.to_numeric(nba_grouped['Population 2016']) # pass in metropolitan area population from cities
win_loss_by_region = nba_grouped['W/L Ratio'] # pass in win/loss ratio from nhl_df in the same order as cities["Metropolitan area"]

assert len(population_by_region) == len(win_loss_by_region), "Q2: Your lists must be the same length"
assert len(population_by_region) == 28, "Q2: There should be 28 teams being analysed for NBA"

return stats.pearsonr(population_by_region, win_loss_by_region)

cities_nba

In [ ]:
cities=pd.read_html("wikipedia_data.html")[1]
cities=cities.iloc[:-1,[0,3,5,6,7,8]]

cities = cities.replace(to_replace="\[.*?\]", value= "", regex= True )
cities = cities.replace(to_replace="(?<=[a-z])(?=[A-Z])", value=" ", regex=True) #locally I got texts like "GianJets" instead of "Giant Jets" so I added a space between lower and upper case letters

#REMOVING BLANK SPACES FROM THE COLUMNS
cities.columns = cities.columns.str.strip()

cities.rename(columns = {'Population (2016 est.)[8]': 'Population 2016'}, inplace=True)

In [ ]:
cities_nba = cities.copy()[['Metropolitan area', 'NBA', 'Population 2016']] #we gotta create a copy to avoid an error

#separating the teams in a region
cities_nba['NBA'] = cities['NBA'].str.split(' ')
cities_nba = cities_nba.explode('NBA')

#further cleaning the data
cities_nba.replace('—', np.nan, inplace=True) #There are data missing for some cities.
cities_nba.replace('', np.nan, inplace=True)
cities_nba.dropna(inplace=True)
cities_nba

In [ ]:
#2) NHL DATA. WORKING OUT THE DATA FOR THE NATIONAL HOCKEY TEAMS. YEAR 2018
nba_df=pd.read_csv("nba.csv")
nba_df = nba_df[nba_df["year"] == 2018]
nba_df.head(nba_df.shape[0])

In [ ]:
nba_df.replace(to_replace="\*", value = "", regex=True, inplace=True)
nba_df = nba_df.replace(to_replace="\(.*?\)", value= "", regex= True )
nba_df['team'] = nba_df['team'].str.split().str[-1] #selecting the last word that denominates the team's name
nba_df

In [ ]:
nba_df = nba_df[["team", "W", "L"]]
nba_df["W"] = pd.to_numeric(nba_df["W"])
nba_df["L"] = pd.to_numeric(nba_df["L"])
nba_df["W/L Ratio"] = nba_df["W"]/(nba_df["L"]+nba_df["W"]) #creaing the W/L Ratio column we need. This can be replace by the dataframe own column
nba_df

In [ ]:
#3) joining the NHL data with the metropolitan area data, and filtering out the metropolitan areas that are not in the NHL data:
nba_merged = pd.merge(nba_df, cities_nba, how='inner', left_on='team', right_on='NBA')
nba_merged

In [ ]:
nba_grouped = nba_merged.groupby('Metropolitan area').agg({'Population 2016': 'first' , 'W/L Ratio': np.mean})
nba_grouped.reset_index(inplace=True) #if we don't do this the cities are gonna be the indexes
nba_grouped

In [23]:
cities = cities.replace(to_replace="\[.*?\]", value= "", regex= True )
cities = cities.replace(to_replace="(?<=[a-z])(?=[A-Z])", value=" ", regex=True) #locally I got texts like "GianJets" instead of "Giant Jets" so I added a space between lower and upper case letters
cities.rename(columns = {'Population (2016 est.)[8]': 'Population 2016'}, inplace=True)

def nba_correlation():
    #1) WORKING OUT THE CITIES DATA
    cities_nba = cities.copy()[['Metropolitan area', 'NBA', 'Population 2016']] #we gotta create a copy to avoid an error

    #separating the teams in a region
    cities_nba['NBA'] = cities['NBA'].str.split(' ')
    cities_nba = cities_nba.explode('NBA')

    #further cleaning the data
    cities_nba.replace('—', np.nan, inplace=True) #There are data missing for some cities.
    cities_nba.replace('', np.nan, inplace=True)
    cities_nba.dropna(inplace=True)
   
    #2) NHL DATA. WORKING OUT THE DATA FOR THE NATIONAL HOCKEY TEAMS. YEAR 2018
    nba_df=pd.read_csv("nba.csv")
    nba_df = nba_df[nba_df["year"] == 2018]
    nba_df.head(nba_df.shape[0])
    nba_df.replace(to_replace="\*", value = "", regex=True, inplace=True)
    nba_df = nba_df.replace(to_replace="\(.*?\)", value= "", regex= True )
    nba_df['team'] = nba_df['team'].str.split().str[-1] #selecting the last word that denominates the team's name
    nba_df = nba_df[["team", "W", "L"]]
    nba_df["W"] = pd.to_numeric(nba_df["W"])
    nba_df["L"] = pd.to_numeric(nba_df["L"])
    nba_df["W/L Ratio"] = nba_df["W"]/(nba_df["L"]+nba_df["W"]) #creaing the W/L Ratio column we need. This can be replace by the dataframe own column
    #3) joining the NHL data with the metropolitan area data, and filtering out the metropolitan areas that are not in the NHL data:
    nba_merged = pd.merge(nba_df, cities_nba, how='inner', left_on='team', right_on='NBA')
    nba_grouped = nba_merged.groupby('Metropolitan area').agg({'Population 2016': 'first' , 'W/L Ratio': np.mean})
    nba_grouped.reset_index(inplace=True) #if we don't do this the cities are gonna be the indexes


    population_by_region = pd.to_numeric(nba_grouped['Population 2016']) # pass in metropolitan area population from cities
    win_loss_by_region = nba_grouped["W/L Ratio"] # pass in win/loss ratio from nba_df in the same order as cities["Metropolitan area"]

    assert len(population_by_region) == len(win_loss_by_region), "Q2: Your lists must be the same length"
    assert len(population_by_region) == 28, "Q2: There should be 28 teams being analysed for NBA"

    return stats.pearsonr(population_by_region, win_loss_by_region)

nba_correlation()

(-0.17657160252844611, 0.3687474160446298)

## Question 3
For this question, calculate the win/loss ratio's correlation with the population of the city it is in for the **MLB** using **2018** data.

In [66]:
import pandas as pd
import numpy as np
import scipy.stats as stats
import re

mlb_df=pd.read_csv("mlb.csv")
cities=pd.read_html("wikipedia_data.html")[1]
cities=cities.iloc[:-1,[0,3,5,6,7,8]]

cities = cities.replace(to_replace="\[.*?\]", value= "", regex= True )
cities = cities.replace(to_replace="(?<=[a-z])(?=[A-Z])", value=" ", regex=True) #locally I got texts like "GianJets" instead of "Giant Jets" so I added a space between lower and upper case letters
cities.rename(columns = {'Population (2016 est.)[8]': 'Population 2016'}, inplace=True)

#REMOVING BLANK SPACES FROM THE COLUMNS
cities.columns = cities.columns.str.strip()

def mlb_correlation(): 
    
    #1) WORKING OUT THE CITIES DATA
    cities_mlb = cities.copy()[['Metropolitan area', 'MLB', 'Population 2016']] #we gotta create a copy to avoid an error

    #separating the teams in a region
    cities_mlb['MLB'] = cities_mlb['MLB'].str.split(' ')
    cities_mlb = cities_mlb.explode('MLB')

    #further cleaning the data
    cities_mlb.replace('—', np.nan, inplace=True) #There are data missing for some cities.
    cities_mlb.replace('', np.nan, inplace=True)
    cities_mlb.dropna(inplace=True)
    
    #2) NHL DATA. WORKING OUT THE DATA FOR THE NATIONAL HOCKEY TEAMS. YEAR 2018
    mlb_df=pd.read_csv("mlb.csv")
    mlb_df = mlb_df[mlb_df["year"] == 2018]
    
    mlb_df['team'] = mlb_df['team'].str.split().str[-1] #selecting the last word that denominates the team's name
    mlb_df = mlb_df[["team", "W", "L"]]
    mlb_df["W"] = pd.to_numeric(mlb_df["W"])
    mlb_df["L"] = pd.to_numeric(mlb_df["L"])
    mlb_df["W/L Ratio"] = mlb_df["W"]/(mlb_df["L"]+mlb_df["W"]) #creaing the W/L Ratio column we need. This can be replace by the dataframe own column
    
    #3) joining the NHL data with the metropolitan area data, and filtering out the metropolitan areas that are not in the NHL data:
    mlb_merged = pd.merge(mlb_df, cities_mlb, how='inner', left_on='team', right_on='MLB')
    mlb_grouped = mlb_merged.groupby('Metropolitan area').agg({'Population 2016': 'first' , 'W/L Ratio': np.mean})
    mlb_grouped.reset_index(inplace=True) #if we don't do this the cities are gonna be the indexes
        
    population_by_region = pd.to_numeric(mlb_grouped['Population 2016']) # pass in metropolitan area population from cities
    win_loss_by_region = mlb_grouped["W/L Ratio"] # pass in win/loss ratio from mlb_df in the same order as cities["Metropolitan area"]

    assert len(population_by_region) == len(win_loss_by_region), "Q3: Your lists must be the same length"
    assert len(population_by_region) == 26, "Q3: There should be 26 teams being analysed for MLB"

    return stats.pearsonr(population_by_region, win_loss_by_region)

mlb_correlation()

(0.2036295173328102, 0.31840050647011003)

In [84]:
#1) WORKING OUT THE CITIES DATA
cities_mlb = cities.copy()[['Metropolitan area', 'MLB', 'Population 2016']] #we gotta create a copy to avoid an error

#replacing Boston Red Sox by BostonSox, etc.
cities_mlb['MLB'] = cities_mlb['MLB'].str.replace('Red Sox', 'RedSox')
cities_mlb['MLB'] = cities_mlb['MLB'].str.replace('White Sox', 'WhiteSox')

#separating the teams in a region
cities_mlb['MLB'] = cities_mlb['MLB'].str.split(' ')
cities_mlb = cities_mlb.explode('MLB')

#further cleaning the data
cities_mlb.replace('—', np.nan, inplace=True) #There are data missing for some cities.
cities_mlb.replace('', np.nan, inplace=True)
cities_mlb.dropna(inplace=True)
cities_mlb

         Metropolitan area           MLB Population 2016
0            New York City       Yankees        20153634
0            New York City          Mets        20153634
1              Los Angeles       Dodgers        13310447
1              Los Angeles        Angels        13310447
2   San Francisco Bay Area        Giants         6657982
2   San Francisco Bay Area     Athletics         6657982
3                  Chicago          Cubs         9512999
3                  Chicago      WhiteSox         9512999
4        Dallas–Fort Worth       Rangers         7233323
5         Washington, D.C.     Nationals         6131977
6             Philadelphia      Phillies         6070500
7                   Boston        RedSox         4794447
8   Minneapolis–Saint Paul         Twins         3551036
9                   Denver       Rockies         2853077
10   Miami–Fort Lauderdale       Marlins         6066387
11                 Phoenix  Diamondbacks         4661537
12                 Detroit        Tigers         4297617
13                 Toronto          Blue         5928040
13                 Toronto          Jays         5928040
14                 Houston        Astros         6772470
15                 Atlanta        Braves         5789700
16          Tampa Bay Area          Rays         3032171
17              Pittsburgh       Pirates         2342299
18               Cleveland       Indians         2055612
19                 Seattle      Mariners         3798902
20              Cincinnati          Reds         2165139
21             Kansas City        Royals         2104509
22               St. Louis     Cardinals         2807002
23               Baltimore       Orioles         2798886
27               Milwaukee       Brewers         1572482
40               San Diego        Padres         3317749

In [96]:
#2) NHL DATA. WORKING OUT THE DATA FOR THE NATIONAL HOCKEY TEAMS. YEAR 2018
mlb_df=pd.read_csv("mlb.csv")
mlb_df = mlb_df[mlb_df["year"] == 2018]
#there are two teams in the mlb_df that ends in Sox. The White Sox and the Red Sox. We need to differentiate them
mlb_df.replace(to_replace="Chicago White Sox", value = "Chicago WhiteSox", regex=True, inplace=True)
#mlb_df.replace(to_replace="Boston Red Sox", value = "Boston RedSox", regex=True, inplace=True)

mlb_df.head(mlb_df.shape[0])

                     team    W    L   W-L%    GB  year League
0           Boston RedSox  108   54  0.667    --  2018    MLB
1        New York Yankees  100   62  0.617   8.0  2018    MLB
2          Tampa Bay Rays   90   72  0.556  18.0  2018    MLB
3       Toronto Blue Jays   73   89  0.451  35.0  2018    MLB
4       Baltimore Orioles   47  115  0.290  61.0  2018    MLB
5       Cleveland Indians   91   71  0.562    --  2018    MLB
6         Minnesota Twins   78   84  0.481  13.0  2018    MLB
7          Detroit Tigers   64   98  0.395  27.0  2018    MLB
8        Chicago WhiteSox   62  100  0.383  29.0  2018    MLB
9      Kansas City Royals   58  104  0.358  33.0  2018    MLB
10         Houston Astros  103   59  0.636    --  2018    MLB
11      Oakland Athletics   97   65  0.599   6.0  2018    MLB
12       Seattle Mariners   89   73  0.549  14.0  2018    MLB
13     Los Angeles Angels   80   82  0.494  23.0  2018    MLB
14          Texas Rangers   67   95  0.414  36.0  2018    MLB
15         Atlanta Braves   90   72  0.556    --  2018    MLB
16   Washington Nationals   82   80  0.506   8.0  2018    MLB
17  Philadelphia Phillies   80   82  0.494  10.0  2018    MLB
18          New York Mets   77   85  0.475  13.0  2018    MLB
19          Miami Marlins   63   98  0.391  26.5  2018    MLB
20      Milwaukee Brewers   96   67  0.589    --  2018    MLB
21           Chicago Cubs   95   68  0.583   1.0  2018    MLB
22    St. Louis Cardinals   88   74  0.543   7.5  2018    MLB
23     Pittsburgh Pirates   82   79  0.509  13.0  2018    MLB
24        Cincinnati Reds   67   95  0.414  28.5  2018    MLB
25    Los Angeles Dodgers   92   71  0.564    --  2018    MLB
26       Colorado Rockies   91   72  0.558   1.0  2018    MLB
27   Arizona Diamondbacks   82   80  0.506   9.5  2018    MLB
28   San Francisco Giants   73   89  0.451  18.5  2018    MLB
29       San Diego Padres   66   96  0.407  25.5  2018    MLB

In [97]:
mlb_df['team'] = mlb_df['team'].str.split().str[-1] #selecting the last word that denominates the team's name
mlb_df = mlb_df[["team", "W", "L"]]
mlb_df["W"] = pd.to_numeric(mlb_df["W"])
mlb_df["L"] = pd.to_numeric(mlb_df["L"])
mlb_df["W/L Ratio"] = mlb_df["W"]/(mlb_df["L"]+mlb_df["W"]) #creaing the W/L Ratio column we need. This can be replace by the dataframe own column
mlb_df

            team    W    L  W/L Ratio
0         RedSox  108   54   0.666667
1        Yankees  100   62   0.617284
2           Rays   90   72   0.555556
3           Jays   73   89   0.450617
4        Orioles   47  115   0.290123
5        Indians   91   71   0.561728
6          Twins   78   84   0.481481
7         Tigers   64   98   0.395062
8       WhiteSox   62  100   0.382716
9         Royals   58  104   0.358025
10        Astros  103   59   0.635802
11     Athletics   97   65   0.598765
12      Mariners   89   73   0.549383
13        Angels   80   82   0.493827
14       Rangers   67   95   0.413580
15        Braves   90   72   0.555556
16     Nationals   82   80   0.506173
17      Phillies   80   82   0.493827
18          Mets   77   85   0.475309
19       Marlins   63   98   0.391304
20       Brewers   96   67   0.588957
21          Cubs   95   68   0.582822
22     Cardinals   88   74   0.543210
23       Pirates   82   79   0.509317
24          Reds   67   95   0.413580
25       Dodgers   92   71   0.564417
26       Rockies   91   72   0.558282
27  Diamondbacks   82   80   0.506173
28        Giants   73   89   0.450617
29        Padres   66   96   0.407407

In [89]:
#3) joining the NHL data with the metropolitan area data, and filtering out the metropolitan areas that are not in the NHL data:
mlb_merged = pd.merge(mlb_df, cities_mlb, how='inner', left_on='team', right_on='MLB')
mlb_grouped = mlb_merged.groupby('Metropolitan area').agg({'Population 2016': 'first' , 'W/L Ratio': np.mean})
mlb_grouped.reset_index(inplace=True) #if we don't do this the cities are gonna be the indexes
mlb_grouped

         Metropolitan area Population 2016  W/L Ratio
0                  Atlanta         5789700   0.555556
1                Baltimore         2798886   0.290123
2                  Chicago         9512999   0.482769
3               Cincinnati         2165139   0.413580
4                Cleveland         2055612   0.561728
5        Dallas–Fort Worth         7233323   0.413580
6                   Denver         2853077   0.558282
7                  Detroit         4297617   0.395062
8                  Houston         6772470   0.635802
9              Kansas City         2104509   0.358025
10             Los Angeles        13310447   0.529122
11   Miami–Fort Lauderdale         6066387   0.391304
12               Milwaukee         1572482   0.588957
13  Minneapolis–Saint Paul         3551036   0.481481
14           New York City        20153634   0.546296
15            Philadelphia         6070500   0.493827
16                 Phoenix         4661537   0.506173
17              Pittsburgh         2342299   0.509317
18               San Diego         3317749   0.407407
19  San Francisco Bay Area         6657982   0.524691
20                 Seattle         3798902   0.549383
21               St. Louis         2807002   0.543210
22          Tampa Bay Area         3032171   0.555556
23                 Toronto         5928040   0.450617
24        Washington, D.C.         6131977   0.506173

In [90]:
population_by_region = pd.to_numeric(mlb_grouped['Population 2016']) # pass in metropolitan area population from cities
win_loss_by_region = mlb_grouped["W/L Ratio"] # pass in win/loss ratio from mlb_df in the same order as cities["Metropolitan area"]


stats.pearsonr(population_by_region, win_loss_by_region)

(0.1768311649852326, 0.39778515984791274)

In [68]:
cities = cities.replace(to_replace="\[.*?\]", value= "", regex= True )
cities = cities.replace(to_replace="(?<=[a-z])(?=[A-Z])", value=" ", regex=True) #locally I got texts like "GianJets" instead of "Giant Jets" so I added a space between lower and upper case letters
cities.rename(columns = {'Population (2016 est.)[8]': 'Population 2016'}, inplace=True)

def mlb_correlation(): 
    
    #1) WORKING OUT THE CITIES DATA
    cities_mlb = cities.copy()[['Metropolitan area', 'MLB', 'Population 2016']] #we gotta create a copy to avoid an error

    #separating the teams in a region
    cities_mlb['MLB'] = cities_mlb['MLB'].str.split(' ')
    cities_mlb = cities_mlb.explode('MLB')

    #further cleaning the data
    cities_mlb.replace('—', np.nan, inplace=True) #There are data missing for some cities.
    cities_mlb.replace('', np.nan, inplace=True)
    cities_mlb.dropna(inplace=True)
    
    #2) NHL DATA. WORKING OUT THE DATA FOR THE NATIONAL HOCKEY TEAMS. YEAR 2018
    mlb_df=pd.read_csv("mlb.csv")
    mlb_df = mlb_df[mlb_df["year"] == 2018]
    
    mlb_df['team'] = mlb_df['team'].str.split().str[-1] #selecting the last word that denominates the team's name
    mlb_df = mlb_df[["team", "W", "L"]]
    mlb_df["W"] = pd.to_numeric(mlb_df["W"])
    mlb_df["L"] = pd.to_numeric(mlb_df["L"])
    mlb_df["W/L Ratio"] = mlb_df["W"]/(mlb_df["L"]+mlb_df["W"]) #creaing the W/L Ratio column we need. This can be replace by the dataframe own column
    
    #3) joining the NHL data with the metropolitan area data, and filtering out the metropolitan areas that are not in the NHL data:
    mlb_merged = pd.merge(mlb_df, cities_mlb, how='inner', left_on='team', right_on='MLB')
    mlb_grouped = mlb_merged.groupby('Metropolitan area').agg({'Population 2016': 'first' , 'W/L Ratio': np.mean})
    mlb_grouped.reset_index(inplace=True) #if we don't do this the cities are gonna be the indexes
        
    population_by_region = pd.to_numeric(mlb_grouped['Population 2016']) # pass in metropolitan area population from cities
    win_loss_by_region = mlb_grouped["W/L Ratio"] # pass in win/loss ratio from mlb_df in the same order as cities["Metropolitan area"]

    assert len(population_by_region) == len(win_loss_by_region), "Q3: Your lists must be the same length"
    assert len(population_by_region) == 26, "Q3: There should be 26 teams being analysed for MLB"

    return stats.pearsonr(population_by_region, win_loss_by_region)

mlb_correlation()

(0.2036295173328102, 0.31840050647011003)

# CORRECTION USING THE COLUMN FROM THE DATAFRAME

In [72]:
cities = cities.replace(to_replace="\[.*?\]", value= "", regex= True )
cities = cities.replace(to_replace="(?<=[a-z])(?=[A-Z])", value=" ", regex=True) #locally I got texts like "GianJets" instead of "Giant Jets" so I added a space between lower and upper case letters
cities.rename(columns = {'Population (2016 est.)[8]': 'Population 2016'}, inplace=True)

def mlb_correlation(): 
    
    #1) WORKING OUT THE CITIES DATA
    cities_mlb = cities.copy()[['Metropolitan area', 'MLB', 'Population 2016']] #we gotta create a copy to avoid an error

    #separating the teams in a region
    cities_mlb['MLB'] = cities_mlb['MLB'].str.split(' ')
    cities_mlb = cities_mlb.explode('MLB')

    #further cleaning the data
    cities_mlb.replace('—', np.nan, inplace=True) #There are data missing for some cities.
    cities_mlb.replace('', np.nan, inplace=True)
    cities_mlb.dropna(inplace=True)
    
    #2) NHL DATA. WORKING OUT THE DATA FOR THE NATIONAL HOCKEY TEAMS. YEAR 2018
    mlb_df=pd.read_csv("mlb.csv")
    mlb_df = mlb_df[mlb_df["year"] == 2018]
    
    mlb_df['team'] = mlb_df['team'].str.split().str[-1] #selecting the last word that denominates the team's name
    mlb_df = mlb_df[["team", "W", "L", "W-L%"]]
    mlb_df["W"] = pd.to_numeric(mlb_df["W"])
    mlb_df["L"] = pd.to_numeric(mlb_df["L"])
    mlb_df["W-L%"] = pd.to_numeric(mlb_df["W-L%"])
    #mlb_df["W/L Ratio"] = mlb_df["W-L Ratio"] #mlb_df["W"]/(mlb_df["L"]+mlb_df["W"]) #creaing the W/L Ratio column we need. This can be replace by the dataframe own column
    
    #3) joining the NHL data with the metropolitan area data, and filtering out the metropolitan areas that are not in the NHL data:
    mlb_merged = pd.merge(mlb_df, cities_mlb, how='inner', left_on='team', right_on='MLB')
    mlb_grouped = mlb_merged.groupby('Metropolitan area').agg({'Population 2016': 'first' , 'W-L%': np.mean})
    mlb_grouped.reset_index(inplace=True) #if we don't do this the cities are gonna be the indexes
        
    population_by_region = pd.to_numeric(mlb_grouped['Population 2016']) # pass in metropolitan area population from cities
    win_loss_by_region = mlb_grouped["W-L%"] # pass in win/loss ratio from mlb_df in the same order as cities["Metropolitan area"]

    assert len(population_by_region) == len(win_loss_by_region), "Q3: Your lists must be the same length"
    assert len(population_by_region) == 26, "Q3: There should be 26 teams being analysed for MLB"

    return stats.pearsonr(population_by_region, win_loss_by_region)

mlb_correlation()

(0.2033844345565, 0.3189958564567271)

In [73]:
#1) WORKING OUT THE CITIES DATA
cities_mlb = cities.copy()[['Metropolitan area', 'MLB', 'Population 2016']] #we gotta create a copy to avoid an error

#separating the teams in a region
cities_mlb['MLB'] = cities_mlb['MLB'].str.split(' ')
cities_mlb = cities_mlb.explode('MLB')

#further cleaning the data
cities_mlb.replace('—', np.nan, inplace=True) #There are data missing for some cities.
cities_mlb.replace('', np.nan, inplace=True)
cities_mlb.dropna(inplace=True)

#2) NHL DATA. WORKING OUT THE DATA FOR THE NATIONAL HOCKEY TEAMS. YEAR 2018
mlb_df=pd.read_csv("mlb.csv")
mlb_df = mlb_df[mlb_df["year"] == 2018]

mlb_df['team'] = mlb_df['team'].str.split().str[-1] #selecting the last word that denominates the team's name
mlb_df = mlb_df[["team", "W", "L"]]
mlb_df["W"] = pd.to_numeric(mlb_df["W"])
mlb_df["L"] = pd.to_numeric(mlb_df["L"])
mlb_df["W/L Ratio"] = mlb_df["W"]/(mlb_df["L"]+mlb_df["W"]) #creaing the W/L Ratio column we need. This can be replace by the dataframe own column

#3) joining the NHL data with the metropolitan area data, and filtering out the metropolitan areas that are not in the NHL data:
mlb_merged = pd.merge(mlb_df, cities_mlb, how='inner', left_on='team', right_on='MLB')
mlb_grouped = mlb_merged.groupby('Metropolitan area').agg({'Population 2016': 'first' , 'W/L Ratio': np.mean})
mlb_grouped.reset_index(inplace=True) #if we don't do this the cities are gonna be the indexes

mlb_grouped

         Metropolitan area Population 2016  W/L Ratio
0                  Atlanta         5789700   0.555556
1                Baltimore         2798886   0.290123
2                   Boston         4794447   0.524691
3                  Chicago         9512999   0.544068
4               Cincinnati         2165139   0.413580
5                Cleveland         2055612   0.561728
6        Dallas–Fort Worth         7233323   0.413580
7                   Denver         2853077   0.558282
8                  Detroit         4297617   0.395062
9                  Houston         6772470   0.635802
10             Kansas City         2104509   0.358025
11             Los Angeles        13310447   0.529122
12   Miami–Fort Lauderdale         6066387   0.391304
13               Milwaukee         1572482   0.588957
14  Minneapolis–Saint Paul         3551036   0.481481
15           New York City        20153634   0.546296
16            Philadelphia         6070500   0.493827
17                 Phoenix         4661537   0.506173
18              Pittsburgh         2342299   0.509317
19               San Diego         3317749   0.407407
20  San Francisco Bay Area         6657982   0.524691
21                 Seattle         3798902   0.549383
22               St. Louis         2807002   0.543210
23          Tampa Bay Area         3032171   0.555556
24                 Toronto         5928040   0.450617
25        Washington, D.C.         6131977   0.506173

## Question 4
For this question, calculate the win/loss ratio's correlation with the population of the city it is in for the **NFL** using **2018** data.

In [ ]:
import pandas as pd
import numpy as np
import scipy.stats as stats
import re

nfl_df=pd.read_csv("assets/nfl.csv")
cities=pd.read_html("assets/wikipedia_data.html")[1]
cities=cities.iloc[:-1,[0,3,5,6,7,8]]

def nfl_correlation(): 
    # YOUR CODE HERE
    raise NotImplementedError()
    
    population_by_region = [] # pass in metropolitan area population from cities
    win_loss_by_region = [] # pass in win/loss ratio from nfl_df in the same order as cities["Metropolitan area"]

    assert len(population_by_region) == len(win_loss_by_region), "Q4: Your lists must be the same length"
    assert len(population_by_region) == 29, "Q4: There should be 29 teams being analysed for NFL"

    return stats.pearsonr(population_by_region, win_loss_by_region)

In [30]:
cities = cities.replace(to_replace="\[.*?\]", value= "", regex= True )
cities = cities.replace(to_replace="(?<=[a-z])(?=[A-Z])", value=" ", regex=True) #locally I got texts like "GianJets" instead of "Giant Jets" so I added a space between lower and upper case letters
cities.rename(columns = {'Population (2016 est.)[8]': 'Population 2016'}, inplace=True)
cities

,Metropolitan area,Population 2016,NFL,MLB,NBA,NHL
0,New York City,20153634,Giants Jets,Yankees Mets,Knicks Nets,Rangers Islanders Devils
1,Los Angeles,13310447,Rams Chargers,Dodgers Angels,Lakers Clippers,Kings Ducks
2,San Francisco Bay Area,6657982,49ers Raiders,Giants Athletics,Warriors,Sharks
3,Chicago,9512999,Bears,Cubs White Sox,Bulls,Blackhawks
4,Dallas–Fort Worth,7233323,Cowboys,Rangers,Mavericks,Stars
5,"Washington, D.C.",6131977,Redskins,Nationals,Wizards,Capitals
6,Philadelphia,6070500,Eagles,Phillies,76ers,Flyers
7,Boston,4794447,Patriots,Red Sox,Celtics,Bruins
8,Minneapolis–Saint Paul,3551036,Vikings,Twins,Timberwolves,Wild
9,Denver,2853077,Broncos,Rockies,Nuggets,Avalanche
10,Miami–Fort Lauderdale,6066387,Dolphins,Marlins,Heat,Panthers
11,Phoenix,4661537,Cardinals,Diamondbacks,Suns,Coyotes
12,Detroit,4297617,Lions,Tigers,Pistons,Red Wings
13,Toronto,5928040,—,Blue Jays,Raptors,Maple Leafs
14,Houston,6772470,Texans,Astros,Rockets,—
15,Atlanta,5789700,Falcons,Braves,Hawks,
16,Tampa Bay Area,3032171,Buccaneers,Rays,—,Lightning
17,Pittsburgh,2342299,Steelers,Pirates,,Penguins
18,Cleveland,2055612,Browns,Indians,Cavaliers,
19,Seattle,3798902,Seahawks,Mariners,,
20,Cincinnati,2165139,Bengals,Reds,,—
21,Kansas City,2104509,Chiefs,Royals,,
22,St. Louis,2807002,,Cardinals,,Blues
23,Baltimore,2798886,Ravens,Orioles,,—
24,Charlotte,2474314,Panthers,—,Hornets,—
25,Indianapolis,2004230,Colts,,Pacers,—
26,Nashville,1865298,Titans,—,—,Predators
27,Milwaukee,1572482,,Brewers,Bucks,—
28,New Orleans,1268883,Saints,—,Pelicans,—
29,Buffalo,1132804,Bills,,,Sabres
30,Montreal,4098927,—,,—,Canadiens
31,Vancouver,2463431,—,—,,Canucks
32,Orlando,2441257,—,—,Magic,—
33,Portland,2424955,—,—,Trail Blazers,—
34,Columbus,2041520,—,—,—,Blue Jackets
35,Calgary,1392609,—,—,—,Flames
36,Ottawa,1323783,—,—,—,Senators
37,Edmonton,1321426,—,—,—,Oilers
38,Salt Lake City,1186187,—,—,Jazz,—
39,Winnipeg,778489,—,—,—,Jets
40,San Diego,3317749,,Padres,,—
41,San Antonio,2429609,,—,Spurs,—
42,Sacramento,2296418,—,—,Kings,—
43,Las Vegas,2155664,,—,—,Golden Knights
44,Jacksonville,1478212,Jaguars,—,—,—
45,Oklahoma City,1373211,—,—,Thunder,—
46,Memphis,1342842,,—,Grizzlies,—
47,Raleigh,1302946,—,—,—,Hurricanes
48,Green Bay,318236,Packers,—,—,—
49,Hamilton,747545,—,—,—,
50,Regina,236481,—,—,—,—

In [46]:
#1) WORKING OUT THE CITIES DATA
cities_nfl = cities.copy()[['Metropolitan area', 'NFL', 'Population 2016']] #we gotta create a copy to avoid an error

#separating the teams in a region
cities_nfl['NFL'] = cities_nfl['NFL'].str.split(' ')
cities_nfl = cities_nfl.explode('NFL')
#further cleaning the data
cities_nfl.replace('—', np.nan, inplace=True) #There are data missing for some cities.
cities_nfl.replace('', np.nan, inplace=True)
cities_nfl.dropna(inplace=True)
cities_nfl

         Metropolitan area         NFL Population 2016
0            New York City      Giants        20153634
0            New York City        Jets        20153634
1              Los Angeles        Rams        13310447
1              Los Angeles    Chargers        13310447
2   San Francisco Bay Area       49ers         6657982
2   San Francisco Bay Area     Raiders         6657982
3                  Chicago       Bears         9512999
4        Dallas–Fort Worth     Cowboys         7233323
5         Washington, D.C.    Redskins         6131977
6             Philadelphia      Eagles         6070500
7                   Boston    Patriots         4794447
8   Minneapolis–Saint Paul     Vikings         3551036
9                   Denver     Broncos         2853077
10   Miami–Fort Lauderdale    Dolphins         6066387
11                 Phoenix   Cardinals         4661537
12                 Detroit       Lions         4297617
14                 Houston      Texans         6772470
15                 Atlanta     Falcons         5789700
16          Tampa Bay Area  Buccaneers         3032171
17              Pittsburgh    Steelers         2342299
18               Cleveland      Browns         2055612
19                 Seattle    Seahawks         3798902
20              Cincinnati     Bengals         2165139
21             Kansas City      Chiefs         2104509
23               Baltimore      Ravens         2798886
24               Charlotte    Panthers         2474314
25            Indianapolis       Colts         2004230
26               Nashville      Titans         1865298
28             New Orleans      Saints         1268883
29                 Buffalo       Bills         1132804
44            Jacksonville     Jaguars         1478212
48               Green Bay     Packers          318236

In [53]:
#2) NFL DATA. WORKING OUT THE DATA FOR THE NATIONAL FOOTBALL TEAMS. YEAR 2018
nfl_df=pd.read_csv("nfl.csv")
nfl_df = nfl_df[nfl_df["year"] == 2018]
nfl_df.drop(axis=0,  index = [0, 5, 10, 15, 20, 25, 30, 35], inplace=True) # dropping the rows specifying the divisions.
nfl_df

,DSRS,L,League,MoV,OSRS,PA,PD,PF,SRS,SoS,T,W,W-L%,team,year
1,2.1,5,NFL,6.9,3.1,325,111,436,5.2,-1.8,0,11,.688,New England Patriots*,2018
2,-5.2,9,NFL,-7.1,-3.6,433,-114,319,-8.8,-1.7,0,7,.438,Miami Dolphins,2018
3,-0.6,10,NFL,-6.6,-6.3,374,-105,269,-6.9,-0.3,0,6,.375,Buffalo Bills,2018
4,-5.9,12,NFL,-6.8,-2.0,441,-108,333,-7.8,-1.1,0,4,.250,New York Jets,2018
6,6.4,6,NFL,6.4,0.6,287,102,389,7.0,0.6,0,10,.625,Baltimore Ravens*,2018
7,1.7,6,NFL,4.3,3.9,360,68,428,5.6,1.3,1,9,.594,Pittsburgh Steelers,2018
8,0.6,8,NFL,-2.1,-1.0,392,-33,359,-0.3,1.7,1,7,.469,Cleveland Browns,2018
9,-3.4,10,NFL,-5.4,0.0,455,-87,368,-3.4,2.0,0,6,.375,Cincinnati Bengals,2018
11,1.4,5,NFL,5.4,2.4,316,86,402,3.8,-1.5,0,11,.688,Houston Texans*,2018
12,-0.6,6,NFL,5.6,3.9,344,89,433,3.4,-2.2,0,10,.625,Indianapolis Colts+,2018
13,3.5,7,NFL,0.4,-3.2,303,7,310,0.2,-0.2,0,9,.563,Tennessee Titans,2018
14,4.0,11,NFL,-4.4,-8.1,316,-71,245,-4.0,0.4,0,5,.313,Jacksonville Jaguars,2018
16,-3.8,4,NFL,9.0,12.6,421,144,565,8.9,-0.1,0,12,.750,Kansas City Chiefs*,2018
17,2.9,4,NFL,6.2,3.0,329,99,428,6.0,-0.2,0,12,.750,Los Angeles Chargers+,2018
18,3.1,10,NFL,-1.3,-3.6,349,-20,329,-0.5,0.7,0,6,.375,Denver Broncos,2018
19,-4.1,12,NFL,-11.1,-5.2,467,-177,290,-9.3,1.8,0,4,.250,Oakland Raiders,2018
21,2.9,6,NFL,0.9,-1.9,324,15,339,1.1,0.2,0,10,.625,Dallas Cowboys*,2018
22,1.8,7,NFL,1.2,0.0,348,19,367,1.7,0.5,0,9,.563,Philadelphia Eagles+,2018
23,0.6,9,NFL,-4.9,-5.6,359,-78,281,-4.9,-0.1,0,7,.438,Washington Redskins,2018
24,-2.9,11,NFL,-2.7,0.8,412,-43,369,-2.2,0.5,0,5,.313,New York Giants,2018
26,4.8,4,NFL,8.6,1.5,283,138,421,6.3,-2.3,0,12,.750,Chicago Bears*,2018
27,1.8,7,NFL,1.2,-1.2,341,19,360,0.6,-0.6,1,8,.531,Minnesota Vikings,2018
28,-2.7,9,NFL,-1.5,0.0,400,-24,376,-2.7,-1.2,1,6,.406,Green Bay Packers,2018
29,0.3,10,NFL,-2.3,-3.3,360,-36,324,-3.0,-0.8,0,6,.375,Detroit Lions,2018
31,2.2,3,NFL,9.4,7.9,353,151,504,10.1,0.6,0,13,.813,New Orleans Saints*,2018
32,0.8,9,NFL,-0.4,0.1,382,-6,376,0.9,1.3,0,7,.438,Carolina Panthers,2018
33,-2.6,9,NFL,-0.6,2.5,423,-9,414,-0.1,0.4,0,7,.438,Atlanta Falcons,2018
34,-4.6,11,NFL,-4.3,2.0,464,-68,396,-2.6,1.7,0,5,.313,Tampa Bay Buccaneers,2018
36,-1.1,3,NFL,8.9,9.5,384,143,527,8.5,-0.4,0,13,.813,Los Angeles Rams*,2018
37,1.5,6,NFL,5.1,3.0,347,81,428,4.5,-0.6,0,10,.625,Seattle Seahawks+,2018
38,-3.1,12,NFL,-5.8,-2.5,435,-93,342,-5.5,0.3,0,4,.250,San Francisco 49ers,2018
39,-1.9,13,NFL,-12.5,-9.6,425,-200,225,-11.5,1.0,0,3,.188,Arizona Cardinals,2018

In [62]:
nfl_df.replace(to_replace="\*", value = "", regex=True, inplace=True) #cleaning asterics
nfl_df.replace(to_replace="\+", value = "", regex=True, inplace=True) #cleaning plus signs
nfl_df['team'] = nfl_df['team'].str.split().str[-1] #selecting the last word that denominates the team's name
nfl_df = nfl_df[["team", "W", "L"]]
nfl_df["W"] = pd.to_numeric(nfl_df["W"])
nfl_df["L"] = pd.to_numeric(nfl_df["L"])
nfl_df["W/L Ratio"] = nfl_df["W"]/(nfl_df["L"]+nfl_df["W"]) #creaing the W/L Ratio column we need. This can be replace by the dataframe own column
nfl_df

C:\Users\estef\AppData\Local\Temp\ipykernel_13800\1805904554.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  nfl_df["W"] = pd.to_numeric(nfl_df["W"])
C:\Users\estef\AppData\Local\Temp\ipykernel_13800\1805904554.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  nfl_df["L"] = pd.to_numeric(nfl_df["L"])

          team   W   L  W/L Ratio
1     Patriots  11   5   0.687500
2     Dolphins   7   9   0.437500
3        Bills   6  10   0.375000
4         Jets   4  12   0.250000
6       Ravens  10   6   0.625000
7     Steelers   9   6   0.600000
8       Browns   7   8   0.466667
9      Bengals   6  10   0.375000
11      Texans  11   5   0.687500
12       Colts  10   6   0.625000
13      Titans   9   7   0.562500
14     Jaguars   5  11   0.312500
16      Chiefs  12   4   0.750000
17    Chargers  12   4   0.750000
18     Broncos   6  10   0.375000
19     Raiders   4  12   0.250000
21     Cowboys  10   6   0.625000
22      Eagles   9   7   0.562500
23    Redskins   7   9   0.437500
24      Giants   5  11   0.312500
26       Bears  12   4   0.750000
27     Vikings   8   7   0.533333
28     Packers   6   9   0.400000
29       Lions   6  10   0.375000
31      Saints  13   3   0.812500
32    Panthers   7   9   0.437500
33     Falcons   7   9   0.437500
34  Buccaneers   5  11   0.312500
36        Rams  13   3   0.812500
37    Seahawks  10   6   0.625000
38       49ers   4  12   0.250000
39   Cardinals   3  13   0.187500

In [63]:
#3) joining the NHL data with the metropolitan area data, and filtering out the metropolitan areas that are not in the NHL data:
nfl_merged = pd.merge(nfl_df, cities_nfl, how='inner', left_on='team', right_on='NFL')
nfl_grouped = nfl_merged.groupby('Metropolitan area').agg({'Population 2016': 'first' , 'W/L Ratio': np.mean})
nfl_grouped.reset_index(inplace=True) #if we don't do this the cities are gonna be the indexes

nfl_grouped

         Metropolitan area Population 2016  W/L Ratio
0                  Atlanta         5789700   0.437500
1                Baltimore         2798886   0.625000
2                   Boston         4794447   0.687500
3                  Buffalo         1132804   0.375000
4                Charlotte         2474314   0.437500
5                  Chicago         9512999   0.750000
6               Cincinnati         2165139   0.375000
7                Cleveland         2055612   0.466667
8        Dallas–Fort Worth         7233323   0.625000
9                   Denver         2853077   0.375000
10                 Detroit         4297617   0.375000
11               Green Bay          318236   0.400000
12                 Houston         6772470   0.687500
13            Indianapolis         2004230   0.625000
14            Jacksonville         1478212   0.312500
15             Kansas City         2104509   0.750000
16             Los Angeles        13310447   0.781250
17   Miami–Fort Lauderdale         6066387   0.437500
18  Minneapolis–Saint Paul         3551036   0.533333
19               Nashville         1865298   0.562500
20             New Orleans         1268883   0.812500
21           New York City        20153634   0.281250
22            Philadelphia         6070500   0.562500
23                 Phoenix         4661537   0.187500
24              Pittsburgh         2342299   0.600000
25  San Francisco Bay Area         6657982   0.250000
26                 Seattle         3798902   0.625000
27          Tampa Bay Area         3032171   0.312500
28        Washington, D.C.         6131977   0.437500

In [65]:
nfl_df=pd.read_csv("nfl.csv")
cities=pd.read_html("wikipedia_data.html")[1]
cities=cities.iloc[:-1,[0,3,5,6,7,8]]

cities = cities.replace(to_replace="\[.*?\]", value= "", regex= True )
cities = cities.replace(to_replace="(?<=[a-z])(?=[A-Z])", value=" ", regex=True) #locally I got texts like "GianJets" instead of "Giant Jets" so I added a space between lower and upper case letters
cities.rename(columns = {'Population (2016 est.)[8]': 'Population 2016'}, inplace=True)

def nfl_correlation(): 
    #1) WORKING OUT THE CITIES DATA
    cities_nfl = cities.copy()[['Metropolitan area', 'NFL', 'Population 2016']] #we gotta create a copy to avoid an error

    #separating the teams in a region
    cities_nfl['NFL'] = cities_nfl['NFL'].str.split(' ')
    cities_nfl = cities_nfl.explode('NFL')
    #further cleaning the data
    cities_nfl.replace('—', np.nan, inplace=True) #There are data missing for some cities.
    cities_nfl.replace('', np.nan, inplace=True)
    cities_nfl.dropna(inplace=True)
    cities_nfl
    
    #2) NFL DATA. WORKING OUT THE DATA FOR THE NATIONAL FOOTBALL TEAMS. YEAR 2018
    nfl_df=pd.read_csv("nfl.csv")
    nfl_df = nfl_df[nfl_df["year"] == 2018]
    nfl_df.drop(axis=0,  index = [0, 5, 10, 15, 20, 25, 30, 35], inplace=True) # dropping the rows specifying the divisions.
    
    nfl_df.replace(to_replace="\*", value = "", regex=True, inplace=True) #cleaning asterics
    nfl_df.replace(to_replace="\+", value = "", regex=True, inplace=True) #cleaning plus signs
    nfl_df['team'] = nfl_df['team'].str.split().str[-1] #selecting the last word that denominates the team's name
    nfl_df = nfl_df[["team", "W", "L"]]
    nfl_df["W"] = pd.to_numeric(nfl_df["W"])
    nfl_df["L"] = pd.to_numeric(nfl_df["L"])
    nfl_df["W/L Ratio"] = nfl_df["W"]/(nfl_df["L"]+nfl_df["W"]) #creaing the W/L Ratio column we need. This can be replace by the dataframe own column
    
    #3) joining the NHL data with the metropolitan area data, and filtering out the metropolitan areas that are not in the NHL data:
    nfl_merged = pd.merge(nfl_df, cities_nfl, how='inner', left_on='team', right_on='NFL')
    nfl_grouped = nfl_merged.groupby('Metropolitan area').agg({'Population 2016': 'first' , 'W/L Ratio': np.mean})
    nfl_grouped.reset_index(inplace=True) #if we don't do this the cities are gonna be the indexes

    
    population_by_region = pd.to_numeric(nfl_grouped['Population 2016']) # pass in metropolitan area population from cities
    win_loss_by_region = nfl_grouped["W/L Ratio"] # pass in win/loss ratio from nfl_df in the same order as cities["Metropolitan area"]

    assert len(population_by_region) == len(win_loss_by_region), "Q4: Your lists must be the same length"
    assert len(population_by_region) == 29, "Q4: There should be 29 teams being analysed for NFL"

    return stats.pearsonr(population_by_region, win_loss_by_region)

nfl_correlation()

(0.004922112149349428, 0.9797833458363694)

## Question 5
In this question I would like you to explore the hypothesis that **given that an area has two sports teams in different sports, those teams will perform the same within their respective sports**. How I would like to see this explored is with a series of paired t-tests (so use [`ttest_rel`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.ttest_rel.html)) between all pairs of sports. Are there any sports where we can reject the null hypothesis? Again, average values where a sport has multiple teams in one region. Remember, you will only be including, for each sport, cities which have teams engaged in that sport, drop others as appropriate. This question is worth 20% of the grade for this assignment.

In [ ]:
import pandas as pd
import numpy as np
import scipy.stats as stats
import re

mlb_df=pd.read_csv("assets/mlb.csv")
nhl_df=pd.read_csv("assets/nhl.csv")
nba_df=pd.read_csv("assets/nba.csv")
nfl_df=pd.read_csv("assets/nfl.csv")
cities=pd.read_html("assets/wikipedia_data.html")[1]
cities=cities.iloc[:-1,[0,3,5,6,7,8]]

def sports_team_performance():
    # YOUR CODE HERE
    raise NotImplementedError()
    
    # Note: p_values is a full dataframe, so df.loc["NFL","NBA"] should be the same as df.loc["NBA","NFL"] and
    # df.loc["NFL","NFL"] should return np.nan
    sports = ['NFL', 'NBA', 'NHL', 'MLB']
    p_values = pd.DataFrame({k:np.nan for k in sports}, index=sports)
    
    assert abs(p_values.loc["NBA", "NHL"] - 0.02) <= 1e-2, "The NBA-NHL p-value should be around 0.02"
    assert abs(p_values.loc["MLB", "NFL"] - 0.80) <= 1e-2, "The MLB-NFL p-value should be around 0.80"
    return p_values